- terraform/terraform_account/s3.tf
S3 lifecycle rule clears PDFs from the cache after 1 day. 
Added public access policy to prevent any form of public access to the bucket.
> Added lifecycle rule

- terraform/terraform_environment/ecs_admin.tf
- terraform/terraform_environment/ecs_api.tf
- terraform/terraform_environment/ecs_front.tf
- terraform/terraform_environment/ecs_pdf.tf
Old production assigned the following instances to each part of the service
Service | EC2 Instance
-- | --
admin | T2.medium
api | T2.medium
front | T2.medium
pdf | T2.small
Instance Type | vCPUs | Memory | ECS CPU | ECS Memory
-- | -- | -- | -- | --
T2.medium | 2 | 4GB | 2048 | 4096
T2.small | 1 | 2GB | 1024 | 2048
Update ECS task definitions to match
> update cpu and memory allocation to match old prod

- README.md
- terraform/terraform_environment/ecs_pdf.tf
I've run metrics on PDF generation with sizes 1 vCPU, 2 vCPU & 4 vCPU. 2 vCPU consistently demonstrates a much faster generation time than 1 vCPU, and - oddly - is often faster than 4 vCPU too.
This comes off the back of PDFs taking significantly longer to generation on ECS than EC2.
> Bump PDF's CPU

- terraform/terraform_environment/ecs_front.tf
LPAs should now be tracked from 1 April 2019.
Copy amends are in a separate ticket.
> Track from 1st April 2019

- .circleci/config.yml
The notification occurs too early in the pipeline
> move notification to after healthcheck tests

- service-front/assets/js/moj/moj.modules/moj.analytics.js
It appears this code was always broken but the nature of the breakage hid the problem.
When I duplicated the broken code for the GDS tracking work it became evident.
> Fix the production GA implementation

- service-front/module/Application/view/application/authenticated/lpa/complete/complete.twig
- service-front/module/Application/view/application/authenticated/lpa/complete/view-docs.twig
- service-front/module/Application/view/email/lpa-registration.twig
The 'online LPA ID' number (begins with 'A') is called the 'LPA reference number' in the service. This is incorrect, so I'm amending all references.
> LPA-3572 change LPA reference number to online LPA ID

- terraform/account/autoscaling_role.tf
ECS autoscaling requires a Service Role for autoscaling permissions.
This is an account level shared resource.
Fixes LPA-3420
The PR will bring the role under Terraform management so that further development can continue on PR https://github.com/ministryofjustice/opg-lpa/pull/96
https://docs.aws.amazon.com/IAM/latest/UserGuide/using-service-linked-roles.html
> create an autoscaling role for ecs autoscaling

- docs/runbooks/redeploying_environments/redeploying_environments.md
- docs/runbooks/seeding_non-live_environments.md
Add a run book to provide instructions on how to redeploy an environment
Fixes LPA-3584
A new run book has been created in the `docs` path.
> add instructions for redeploying environments

- terraform/environment/ecs_api.tf
Get admin accounts working correctly in the admin service
Fixes LPA-3571
> Add secret to terraform config for api

- terraform/environment/load_balancer_admin.tf
- terraform/environment/load_balancer_front.tf
The ITHC requires the Auditing company access to non-production services.
Fixes LPA-3597
Create a security group rule for each load balancer allowing ingress from BSI's range.
> Lpa 3597  bsi ingress

- terraform/environment/terraform.tfvars.json
The preproduction environment could not talk to the development of the Sirius API gateway.
Fixes LPA-3620
The preproduction environment was pointed at the development Sirius API gateway, but the ARN for the access policy was incorrect.
> fix arn for preproduction to point to dev gateway

- .circleci/config.yml
- scripts/pipeline/set_environment_variables/set_image_tag.sh
- scripts/pipeline/set_environment_variables/set_terraform_workspace_name.sh
- scripts/pipeline/set_environment_variables/set_workspace.sh
Make the naming of environments and Docker images standard.
Let the pipeline support Dependabot PRs.
Fixes LPA-3711
Use the scripts from UAL and Refunds to produce clean workspace and Docker image names.
> LPA-3711 Script naming of Terraform Workspace and Docker Image Tag

- terraform/environment/terraform.tfvars.json
LPA- 3743
https://opgtransform.atlassian.net/browse/LPA-3743
Fixes LPA-3743
The proprod environment now points to right gateway. 
The proprod environment now points to right gateway. This should now enable receiving responses from Sirius and updating the LPA db and would would then reflect right status on dashboard and status pages for applications.
_Any tips and tricks, blog posts or tools which helped you. Plus anything notable you've discovered about the Refunds service_
> LPA- 3743 Changed permission for gateway access

- .circleci/config.yml
- scripts/pipeline/cancel_previous_jobs/README.md
- scripts/pipeline/cancel_previous_jobs/cancel_redundant_builds.py
To improve pipeline by cancelling running builds of the same type instead of allowing to complete for pr builds
Updated pipeline to cancel job unless its a terraform step
> Auto cancel builds

- Makefile
- README.md
- docker-compose.yml
Remove the need for local.php config file in the lpa-front-app container for local development. 
Fixes LPA-3527
Utilise makefile to fetch secrets directly from aws so theres no need to store them locally or pass them around in files
> LPA 3527 secrets change

- README.md
- service-front/module/Application/config/module.routes.php
- service-front/module/Application/src/Controller/General/HomeController.php
- service-front/module/Application/tests/Controller/General/HomeControllerTest.php
- service-front/module/Application/view/application/general/home/accessibility.twig
- service-front/module/Application/view/layout/twig/layout.twig
_LPA-3752 Create an Accessibility page_
_Add the page, and a link to it in the footer. Works along the same lines as the existing Contact Us page. Test to see that its there, similar to the test for the Contact Us page. Have also done an improvement to the README to include info on how to spin it up with the Sirius API Gateway when needed _
_Learned about the routing and structure of these pages_
> LPA-3752 accessibility page

- service-admin/docker/web/etc/confd/templates/nginx.conf
- service-front/docker/web/etc/confd/templates/nginx.conf
Add standard security headers in nginx 
Fixes LPA-3720
> LPA-3720 - add missing security headers to nginx

- docker-compose.yml
- local-config/start.sh
Fixes issues with localstack, which were found during running the latest version. This does not affect live systems, because the changes only affect development environments. This can be merged safely once reviewed.
Fixes LPA-3762
- Fix port configs to edge port 4566 for localstack
- Workaround issue with http request not returning a value when executing waitforit on 4566. 
- Fix subsequent issue with SQS queue URN configuration changing
There have been a couple of breaking changes in LocalStack, which is used for the queuing and file generation of PDFs.
Since 0.11.6, All traffic now has to go through the AWS edge port (4655), rather than as specified for each service.
See:
- https://github.com/localstack/localstack/pull/2905
- https://github.com/localstack/localstack/issues/2983
Note the …
> Lpa 3762 fix localstack compatibility issues

- terraform/environment/locals.tf
- terraform/environment/rds.tf
- terraform/environment/terraform.tfvars.json
Upgrade postgres version so can be moved to aurora later
Fixes LPA-3447
Upgrading has version matching (version x should move to version y) see https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_UpgradeDBInstance.PostgreSQL.html#USER_UpgradeDBInstance.PostgreSQL.MajorVersion
> Lpa 3447 postgres upgrade

- .circleci/config.yml
Avoid using the deprecated docker version
> Update remote docker version due to deprecation

- scripts/non_live_seeding/seed_environment.sh
_When running locally, seeding has often been failing because the database was not ready_
_Modified the seeding script. This waits for postgres to be ready. It then checks the database exists and warns if not. It then sleeps for a further 20 secs for the tables to be created. This could be improved to do a proper db query for the existence of the table we want to insert into. However, remember this is dev only and a simple sleep likely does the trick. No need for complexity if it doesn't add anything_
_Along the way, doing related work on trying to slim down what starts, I've played with trying to put services into seperate docker-compose files. This isn't straightforward. You then have to always specify files with -f .  Which doesn't work with docker build. So all too easy to forget to …
> LPAL-3 make seeding more robust to db not being ready

- terraform/environment/terraform.tfvars.json
UPGRADE PRODUCTION DATABASE VERSION to PSQL 10.3. DO NOT MERGE UNTIL REQUIRED
Fixes LPA-3447 and LPAL-15
change tfvars.json prod variables for postgres to be 10.13.
Note this is to retrofit the manual change as the path to live takes time.
> LPA-3447  and LPAL-15 PSQL Version to 10.13

- .circleci/config.yml
Add Dockerhub authentication to CircleCI pipeline. See Learning notes and ticket for details.
Fixes LPAL-170
Add details to retrieve env vars with docker credentials, to service authenticated pulls.
We have prerequisite technical guidance, to cover set up steps for this: https://ministryofjustice.github.io/opg-technical-guidance/runbooks/CI_pipelines/adding-ci-dockerhub-users/#adding-a-service-dockerid-to-circleci-build, which we hope to improve in the future.
see also: 
- Using Docker Authenticated Pulls https://circleci.com/docs/2.0/private-images/
> add reference to docker hub credentials + cleanup

- .circleci/config.yml
making a couple of useful fixes whilst i'm in the config.yaml for circleci. 
This is based on:
- conversations with @andrewpearce-digital around `resource_class`
- Use an LPA PR:https://github.com/ministryofjustice/opg-use-an-lpa/pull/590.
2 improvements:
- add a credential manager to docker logins.
- change resource class to small as this is sufficient for our build = less credits spent!
update`config.yaml`
> build pipeline improvements (docker credentials and circleci resource classes)

- scripts/call_api_gateway/.envrc
- scripts/call_api_gateway/README.md
- scripts/call_api_gateway/call_api_gateway.py
to simplify the use call api gateway script, so there is no setup or .envrc needed, to align with UaL. 
This also adds a production switch.
mirror UaL script, which is more fixed. operator role assume is default now.
> simplify running of the call api gateway script, align with UaL

- .circleci/config.yml
refactor so we can reuse build definition for scheduled triggering and path to live build
Fixes LPAL-18
- Use anchor blocks to split out workflow jobs, for reuse.
- Tweak existing workflows to reuse the aliased workflow job blocks
- Add an additional schedule workflow to run weekly on weds early morning.
- YAML anchors and aliases for reuse, doesn't seem to be a good circleCI way to reuse otherwise in circle for entire workflows. 
other options mentioned are available e.g. parameters but don't seem to be suitable for this purpose.
See https://discuss.circleci.com/t/step-reuse-commands-vs-jobs-vs-anchors/33997/2
> LPAL-18 workflow refactor and schedule for weekly deployment

- scripts/non_live_seeding/seed_environment.sh
- terraform/environment/ecs_seeding.tf
- To address the issue with seeding in CircleCI failing on rerun
- To ensure we make it difficult enough to run these scripts on production, as we never need to do that!
Fixes LPAL-182
- Reinstate the truncation of the tables as was previously commented out.
- Add environment variable containing account_name (e.g `development`,`preproduction` or `production`) to the seeding ecs task.
- *Note:* shell script already exits on finding relevant env var value for `production` so just needed reinstating.
- Take out seeding ecs task, and associated egress rule if in `production` as it is not needed.
- *Note:* security group will need further looking at as the config.tf file relies on this for the pipeline, not a major issue.
- conditionals in terraform
> Lpal 182 fix seeding issues

- service-front/package-lock.json
npm audit fix run to remove dependabot alert for object-path.
-  see advisory: https://npmjs.com/advisories/1573.
Github could not raise this automatically.
- npm audit fix
> npm audit fix for dependabot alert object-path

- Makefile
- README.md
- tests/functional/README.md
_LPAL-179 add capability to run functional tests locally from Makefile_
_docker build and docker run to run this locally. Similar to how Circle does it_
> run functional tests locally, from Makefile

- service-admin/docker/app/Dockerfile
- service-api/docker/app/Dockerfile
- service-front/docker/app/Dockerfile
- service-pdf/docker/app/Dockerfile
- tests/Dockerfile
Docker hub had an updated push to composer image, which pushed it to 2.0. this broke our build. 
We will need to pin this for now to 1.10.16, with a view to upgrade to 2.0 after we've done a Laminas Upgrade.
- pin dockerfiles
> pin to specific composer version for now.

- Makefile
_Provide the ability to do a proper clean of the Make environment, get it back to a sane state just like a fresh clone but plus any local code changes. Helps a lot when doing an upgrade, hopefully will make it easier to fix broken local dev environments_
_Makefile now , in dc-build-clean, explicitly removes all the images that will have been left around - Note - rather than do a remove all we delete them by name, so as to leave other images such as localstack intact.  Have added a reset which calls this then does make dc-run, as thats only too easy to forget to do. So to use this we will type make reset in future_
> Clean Make properly

- .circleci/config.yml
issue arose overnight with workspace cleanup. needed to pin this to 0.12.28 as terraform 0.13.5 is enforcing `required_providers` move for pagerduty. we will address this in a later terraform upgrade.
pin workspace cleanup job docker executor to 0.12.28.
> hashicorp upgraded docker image latest to 0.13.5. pinning

- Makefile
- docker-compose.yml
_Improve the reset option to clean up properly, add options to only reset front and only run front unit tests. Make dc-run now runs in parallel. composer uses prestissimo in make dc-run_
_See source files, fairly self-explanatory. _
> Makefile and build speed improvements

- .circleci/config.yml
- terraform/environment/credentials.tf
- terraform/environment/versions.tf
- terraform/terraform_maintenance/live_service_url.tf
Upgrade environment aws providers for version 3.0. 
Fixes LPAL-189
- Remove references to 2.70 of the hashicorp/aws provider
- Add required_provider version to  `~> 3.0` for the aws provider
- note - no state moves required for this PR.
- note - previous provider moves done alongside a separate cycle of PRs for the terraform upgrade. 
- Full documentation check to ensure no resources needed changing.
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-3-upgrade
where terraform state is in S3, in case a roll back needed.
other guidance from:
- https://github.com/ministryofjustice/opg-use-an-lpa/pull/499
- https://github.com/ministryofjustice/opg-use-an-lpa/pull/500
> aws environment provider upgrade

- scripts/pipeline/workspace_cleanup/workspace_cleanup.sh
add `terraform init` to workspace cleanup on selection of workspace in job.
During workspace housekeeping, I noticed we did not initialise workspaces prior to destroy. this can be an issue if the tfstate is on an older version. this fix should resolve this in future.
> additional init step for workspace cleanup

- .circleci/config.yml
- Makefile
- cypress.json
- cypress/Dockerfile
- cypress/integration/basic_login.js
- cypress/integration/home.spec.js
- cypress/support/commands.js
- cypress/support/index.js
_LPAL-6 expand the cypress test to do a11y test(s) as a proof of concept_
_pull in cypress-axe and throw it at login page (which pass) , and home page (which doesn't). Remove pa11y tests from build as this is now superseded by cypress-axe _
> cypress a11y proof of concept

- .circleci/config.yml
To split out the cypress ci step into a parallel job. This allows existing casper tests to continue and allow gradual migration to Cypress tests, with an aim to remove casper when migration completes.
- Duplicate casper/ cypress job steps.
- Remove parts not needed in each job.
- Update job dependancies so that we wait on both test jobs to complete (Fan out / fan back in)
N/A
> LPAL-195 split tests into 2 jobs and redo dependancies

- .circleci/config.yml
- service-pdf/bin/pdftk
- service-pdf/docker/app/Dockerfile
We are seeing a number of vulnerabilities being picked up in the pdf (previously masked by an unknown CVE) container scan. the safest option here is to move to an alpine linux container, which has less in it. This will mean a number of changes as PDFTK is not supported as a package since 3.8 of alpine. 
However there is a maintainer of a java ported version, which we are now using.
This appears to be the recommended approach..
Fixes LPAL-129
- Update dockerfile to Alpine
- Replace install libraries and include those needed for php, xdebug and bash
- Add install of openjdk8-jre to support the java port
- pull version 3.2.1 of the pdftk-java jar
- include executable shell script to sit over the top of the jar file
Context:
- Removal of support for older PDFTK: …
> Lpal 129 vuln fix for pdf container

- scripts/pipeline/check_ecr_scan_results/aws_ecr_scan_results.py
To slightly improve the messaging on the builds for ECR scans. 
Flag up when scan has no results.
python script change.
N/A
> minor improvements to ECR scan messages

- service-seeding/docker/app/Dockerfile
Update the version of Alpine used for the seeding container to fix security alerts thrown by the ECR check in CircleCI.
Fixes LPAL-226
Simple update to the Alpine version in the seeding Dockerfile.
I've run the pipeline with the new Dockerfile and there are no errors due to security issues in the seeding image.
n/a
> LPAL-226 Update alpine version for seeding container

- service-front/package-lock.json
- service-front/package.json
To manually fix dependabot issue for `gulp-browser-sync` which has a transitive dependancy on an earlier version of `axios`,  buried 3 deep.
Required a forced package resolution to replace with a non vulnerable version.
* Fixes LPAL-231
* add `npm-force-resolutions` 
* add `resolutions` section to fix to `axios@0.21.1`
* `npm-force-resolutions`: https://github.com/rogeriochaves/npm-force-resolutions
* `npm-force-resolutions` only works  on `npm<7`, so use this version or node 14 if you change this. see SO comment: https://stackoverflow.com/a/65014694/1249855 
* issue already raised by others on browser-sync repo: https://github.com/BrowserSync/browser-sync/issues/1831
> package.json and lockfile changes - fix axios transitive dependancy

- service-front/module/Application/src/Model/Service/Session/PersistentSessionDetails.php
- service-front/module/Application/src/Module.php
- service-front/module/Application/src/View/Helper/RouteName.php
- service-front/module/Application/src/View/Helper/RouteNameFactory.php
- service-front/module/Application/tests/Model/Service/Session/PersistentSessionDetailsTest.php
- service-front/module/Application/tests/View/Helper/RouteNameFactoryTest.php
As a first time user of the service, when I complete the "my details" page and then directed to the LPA type page, or log in for the first time after having only previously completed ‘my details’, I want to see the page from the top.
The page currently lands/anchors to the ‘What type of LPA’ question header and making it unclear to users that there is content with links above.
Fixes LPAL-23
Creates a breadcrumb system that stores the previously accessed route, which is then passed to the RouteName twig helper function
> LPAL-23 - I want to see that relevant guidance on the LPA type page

- service-front/module/Application/src/Controller/General/PingController.php
Disables warnings from being displayed on health check endpoints
Fixes LPAL-23 and LPAL-267
Changes error_reporting to display only system halting errors, this information is still logged at the infra level
> LPAL-267 Disables warnings from being displayed on health check endpoints

- .circleci/config.yml
to reinstate production based steps and reinstate weekly refresh. this is to go in after PR #219. 
edit circleci config.yml
N/A
> revert last nights breakglass change (depends on #219)

- terraform/account/.terraform.lock.hcl
- terraform/account_ingress/.terraform.lock.hcl
- terraform/email/.terraform.lock.hcl
- terraform/environment/.terraform.lock.hcl
update lock files for terraform to pre-populate both linux and macOS architectures.
Fixes LPAL-276
update lock files for account and environment.
- https://nklya.medium.com/terraform-v0-14-dependency-lock-file-terraform-lock-hcl-gotchas-da8c9dda697 
- https://www.terraform.io/docs/configuration/dependency-lock.html
> LPAL-276 update lock files

- service-front/package-lock.json
- service-front/package.json
forced update socket.io to address dependabot vulnerability.
Fixes LPAL-283
add `socket.io` to `resolutions` in package.json and run `npm install` on node 14.
- see CVE: https://github.com/advisories/GHSA-fxwf-4rqh-v8g3
> LPAL-283 forced dependancy for socket.io

- README.md
- cypress/S3Monitor.py
_Quieten down S3Monitor, updated README_
_use argparse to give S3Monitor a -v option, default to false. Still prints 1 line out so we know at least its running_
> Quieten down S3Monitor, updated README

- service-admin/docker/app/Dockerfile
- service-api/docker/app/Dockerfile
- service-front/docker/app/Dockerfile
- service-pdf/docker/app/Dockerfile
pin php-fpm-alpine to 3.12. this is to see if it removes low severity vulnerability
Fixes LPAL-292
- pin dockerfile in front_app, service_api, service_admin and service_pdf.
- https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-28928
> pin to previous version 3.12 alpine

- .github/dependabot.yml
drop the frequency and increase count of PR's slightly, the schedule is as follows:
- Sunday: composer (up to 2 PR's each)
- Tuesday: docker (1 each)
- Thursday: npm (1 each - though there are issues with this right now)
Fixes LPAL-293
- update `dependabot.yml`
See : https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates
also it is worth exploring the update strategies, but want to do that under a separate ticket. read above for options on `versioning-strategy`
> LPAL-293: change frequency, number and spread load over week of dependabot.

- service-front/composer.lock
- service-pdf/composer.lock
- tests/composer.lock
update all composer minor lockfiles, as listed by the dependabot PR's 
- service-pdf
- service-front
- tests
Fixes LPAL-294
- `composer outdated`
- `composer update` 
N/A
> LPAL-294 update lock files for composer

- terraform/account/put_secrets.tf
- terraform/environment/ecs_front.tf
- terraform/environment/rds.tf
- terraform/environment/secrets.tf
- To create secrets for new endpoint 
- New endpoint env var to make Ordinance Survey api endpoint more configurable.
Part 1 of  LPAL-315
- Add secret placeholder to account. This will then allow us to put new api keys in place.
- Add env vars to ECS front
- Secrets manager: https://docs.aws.amazon.com/secretsmanager/index.html
- OS Places Hub API: https://osdatahub.os.uk/docs
> LPAL-315 migrate to OS Places Hub API

- terraform/environment/cloudwatch_alarms.tf
An additional CloudWatch alarm to check if we have too many pdf messages in the fifo queue.
We may want to add more, but this is a first stab.
- **NOTE**: This may also need a further tweak if too sensitive.
Current threshold is > sum of 6 in an evaluation period (60s).  
Looking at current metrics, we don't tend to get more than 4 in a minute stacked up, so seems like a reasonable attempt.
Fixes LPAL-131
- Add cloudwatch alarm 
- add to pager duty SNS topic
- SQS developer guide - available cloudwatch metrics: https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-available-cloudwatch-metrics.html
> LPAL-131 add PDF message queue cloudwatch alarm for available items

- terraform/environment/ecs_admin.tf
- terraform/environment/ecs_api.tf
- terraform/environment/ecs_api_cron.tf
- terraform/environment/ecs_front.tf
- terraform/environment/ecs_pdf.tf
Pin ECS to Fargate 1.3.0. Failure to do this will mean we are on 1.4.0. we need to test that version out and make appropriate adjustments as needed in a separate ticket.
Fixes LPAL-323
replace `LATEST` tag with `1.3.0`
- AWS Fargate versions: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/platform_versions.html
> pin versions of ECS fargate to 1.3.0

- Makefile
- cypress/Dockerfile
- cypress/integration/CreateHwLpa.feature
- cypress/integration/CreatePfLpa.feature
- cypress/integration/Errors.feature
- cypress/integration/Feedback.feature
- cypress/integration/Password.feature
- cypress/integration/Signup.feature
- cypress/integration/common/a11y.js
- cypress/integration/common/attorney.js
- cypress/support/axe_wrapper.js
- cypress/support/commands.js
- cypress/support/index.js
- service-front/module/Application/view/layout/twig/layout.twig
Add "Error: " to the start of the page title when an error occurred on the page.
https://opgtransform.atlassian.net/browse/LPAL-317
https://opgtransform.atlassian.net/browse/LPAL-278
Fixes LPAL-317, LPAL-278
Simple change to layout template. Additionally worked on cypress tests so I could have passing tests to prove it works (removed cypress-axe in the process).
n/a
> LPAL-317 Show error in page title / LPAL-278 Replace cypress-axe

- docs/pull_request_template.md
- terraform/account/certificate.tf
- terraform/account/locals.tf
- terraform/account/s3.tf
- terraform/account/vpc_flowlogs.tf
- terraform/account/workspace_cleanup.tf
- terraform/email/locals.tf
- terraform/environment/.terraform.lock.hcl
- terraform/environment/autoscaling.tf
- terraform/environment/cloudwatch_alarms.tf
- terraform/environment/dynamo_db.tf
- terraform/environment/ecs_admin.tf
- terraform/environment/ecs_api.tf
- terraform/environment/ecs_api_cron.tf
- terraform/environment/ecs_cluster.tf
- terraform/environment/ecs_front.tf
- terraform/environment/ecs_pdf.tf
- terraform/environment/ecs_seeding.tf
- terraform/environment/load_balancer_admin.tf
- terraform/environment/load_balancer_front.tf
- terraform/environment/locals.tf
- terraform/environment/modules/ecs_autoscaling/main.tf
- terraform/environment/modules/ecs_autoscaling/variables.tf
- terraform/environment/rds.tf
- terraform/environment/resource_group.tf
- terraform/environment/sqs.tf
- terraform/environment/vpc_data.sources.tf
- To improve tagging on our AWS resources, fill any missing gaps.
Fixes LPAL-326
- Tag all the "taggable" AWS resources in infra using `local.default_tags`
- Where possible, assign a component tag, to identify the group of items that go with a specific component of the service.
- Done at Account and Environment level where needed.
- Update Runbook tag with correct repo details.
- Rename outdated term in infra code.
- Also added WoW entry to PR template for tagging resources as a reminder.
N/A
> LPAL-326-tidy-tagging

- terraform/account/cloudwatch.tf
- terraform/account/pagerduty.tf
- terraform/account/sns.tf
AWS ACCOUNT LEVEL CHANGE
to fix issues with the cloudwatch alarm for breakglass alerts.
to ensure we only alert in production for this.
Fixes LPAL-77
- Fix metric name and filter
- Remove dev only restriction to pagerduty ops service
- Apply prod only restriction to the alarm and metric
- formatting 
- cloudwatch metric filters: https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/MonitoringLogData.html
> LPAL-77-fix-alarm-settings

- terraform/environment/cloudwatch_alarms.tf
- terraform/environment/locals.tf
- terraform/environment/pagerduty.tf
- terraform/environment/sns.tf
- To reassign some of the cloudwatch alarms to new Ops based pagerduty.
- To fix and tweak existing cloudwatch alarms.
Fixes LPAL-77
- change the sns topic for relevant alarms
- add integration at environment level for Ops pagerduty.
- fix faulty CSRF alarm and reduce threshold / sampling
- refactor to place SNS in it's own file
- N/A
> LPAL-77 rework some cloudwatch alarms in environment.

- terraform/environment/cloudwatch_alarms.tf
- terraform/environment/ecs_hibernation.tf
- terraform/environment/modules/ecs_scheduled_scaling/main.tf
- terraform/environment/modules/ecs_scheduled_scaling/variables.tf
- terraform/environment/rds.tf
to scale down our dev instances outside peak hours, and at weekends
Fixes LPAL-314
- add module to do schedule scaling
- configure schedule and min maxes as needed. only dev has this.
> Lpal 314 dev scale down ooh

- scripts/pipeline/workspace_cleanup/workspace_cleanup.sh
- terraform/environment/autoscaling.tf
- terraform/environment/ecs_hibernation.tf
- terraform/environment/modules/ecs_autoscaling/variables.tf
- terraform/environment/modules/ecs_scheduled_scaling/main.tf
- terraform/environment/modules/ecs_scheduled_scaling/variables.tf
Dev workspace cleanup failing due to issues with trying to delete the appautoscale target twice. 
This is now an output variable from autoscale module, so that the schedule scale can use this value instead, and will no longer cause an issue.
Without this we have dangling terraform workspaces, which were building up. 
- added an output var to the autoscale to get the required values target
- reworked the scheduled module to take the target values required from the autoscale module.
- terraform output values: https://www.terraform.io/docs/language/values/outputs.html
- aws appautoscaling target TF https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appautoscaling_target
> Urgent rework autoscale to prevent  object not found errors

- scripts/pipeline/start_seeding_task/ecs_start_seeding_task.py
- terraform/environment/cloudwatch_alarms.tf
- terraform/environment/cloudwatch_logs.tf
- terraform/environment/ecs_admin.tf
- terraform/environment/ecs_api.tf
- terraform/environment/ecs_front.tf
- terraform/environment/ecs_pdf.tf
- terraform/environment/ecs_seeding.tf
- terraform/environment/terraform.tfvars.json
- terraform/environment/variables.tf
- Change the log groups to be per environment. this would make it easier to investigate.
- Also improve tagging as this was not present at task level.
Fixes LPAL-125
- Change from account level `online-lpa` log group to `${local.environment}_application_logs` on ECS containers
- We'll keep the account level one for historic purposes
- Tag propagation on tasks (noticed this as missing)
- Remove commented CSRF cloudwatch alarm and filter
- seeding Python scripts changed to accommodate new log group.
- python f' strings: https://realpython.com/python-f-strings/
- tag propagation - you can choose propagate from `TASK_DEFINITION` or `SERVICE`; some resources: 
- https://docs.aws.amazon.com/whitepapers/latest/tagging-best-practices/propagate-tag-values-across-related-resources.html
- …
> Lpal 125 reconfigure application logs + minor additional tagging and cleanup.

- service-front/module/Application/config/module.config.php
- service-front/module/Application/config/module.routes.php
- service-front/module/Application/src/Controller/General/PingController.php
- service-front/module/Application/src/ControllerFactory/ControllerAbstractFactory.php
- service-front/module/Application/src/ControllerFactory/PingControllerFactory.php
- service-front/module/Application/tests/Controller/General/PingControllerTest.php
Errors were occurring due to some session handling nonsense
going on in the AbstractControllerFactory.
By extending the AbstractActionController from Laminas directly
to give us the PingController (we don't need the other machinery
which comes with the AbstractBaseController after all), we can
remove a lot of complexity and create a controller which doesn't
need sessions.
This gets rid of the ini_set exceptions from /ping/json because
we no longer have session stuff going on.
Fixes LPAL-267
Reduce complexity of PingController, which doesn't need session machinery.
n/a
> LPAL-267 Prevent ini_set errors from /ping/json endpoint

- cypress/support/commands.js
- cypress/support/index.js
_LPAL-346 prevent a11y check from being run multiple times on same page _
_Create an empty Set on cypress startup, when doing a11y check ensure url not already in set, run check and add url to set_
> LPAL-346 prevent repetition of a11y checks

- cypress/integration/Guidance.feature
https://opgtransform.atlassian.net/browse/LPAL-357
Fixes LPAL-357
Remove the scenarios. They can always be retrieved later if necessary. I'd suggest only doing this if we can replace all the tab emulation with something native to cypress.
cypress may or may not support this natively at some point
> LPAL-357 Remove Guidance.feature scenarios which regularly fail

- .circleci/config.yml
- scripts/pipeline/set_environment_variables/set_slack_notify_production_release.sh
- scripts/pipeline/set_environment_variables/set_slack_post_environment_domains.sh
- Variables need substitution if they contain multiline strings, and replaced with the literal `\n`
- On top of this, we also needed to properly escape double quotes as this was messing up the orb.
Fixes LPAL-352
- add substitution to `${COMMIT_MESSAGE}` to replace actual end of lines with  a `\n` literal. This is handled better by JQ and the new slack orb.
- use `sed` to escape double quotes in the above  env var. 
- bash variable substitution and removal of new lines: https://stackoverflow.com/questions/19345872/how-to-remove-a-newline-from-a-string-in-bash
- `sed`
Had to take the source of the Orb and place it inline to find the issue with debug statements. This took a fair bit of experimentation to get to work.  
I've raised bugs on the orb for the first issue as i think it needs a …
> Lpal 352 sanitize commit message for new slack orb

- terraform/account/elasticache.tf
Part 1 of
https://opgtransform.atlassian.net/browse/LPAL-336?atlOrigin=eyJpIjoiMGJjZDk3ODdlYmIwNGNlZTg1MjkwMTVmZjY4MmFhZGEiLCJwIjoiaiJ9
Fixes LPAL-336
Replaces DynamoDB with Redis, adds in the required inf first before connecting this up to the app
> LPAL-336 Adds Elasticache as an account level resource

- terraform/account/cloudwatch.tf
- terraform/account/pagerduty.tf
- terraform/account/sns.tf
to add utilization alarms for Elasticache
Fixes LPAL-367
- Create account level alerts for CPU and Swap Utilization
- Pagerduty integration for Elasticache
- create SNS topic
See UaL example: https://github.com/ministryofjustice/opg-use-an-lpa/blob/796c8367c9fba7559de3b26c6a8933c6f1337b07/terraform/account/cloudwatch_alarms.tf
> Elasticache Cloudwatch alarms

- service-admin/docker/app/Dockerfile
- service-api/docker/app/Dockerfile
- service-front/docker/app/Dockerfile
- service-pdf/docker/app/Dockerfile
- tests/Dockerfile
due to an issue with Doctrine and PHP in 7.4.18, we need to pin our PHP version to a last known good - 7.4.16.
pin docker files to a fixed version of PHP
relates to https://bugs.php.net/bug.php?id=81002
> pin to 7.4.16 with a view to removing once issue in next release is resolved

- scripts/pipeline/set_environment_variables/set_slack_notify_production_release.sh
- scripts/pipeline/set_environment_variables/set_slack_post_environment_domains.sh
revisit the slack issue where it fails to send. 
Fixes LPAL-352 (hopefully)
remove variable expansion braces from `$COMMIT_MESSAGE` env var and associated sanitization.
Var expansion not compatible with orb.
> LPAL-352 - revisit issue with slack notifications

- .circleci/config.yml
Fixes [LPAL-394](https://opgtransform.atlassian.net/browse/LPAL-394)
Add exclusion for the @Statuses cypress test tag, as these tests only work in dev right now.
n/a
> LPAL-394 Exclude @Statuses from cypress test suite in path_to_live

- service-admin/docker/app/Dockerfile
- service-api/docker/app/Dockerfile
- service-front/docker/app/Dockerfile
- service-pdf/docker/app/Dockerfile
- tests/Dockerfile
Composer 2.1 was released, which broak phpunit in an unexpected way. this pin is a workaround until the fix is made for this specific issue.
Break-fix
pin dockerfile to `composer:2.0.14`
> pin composer to 2.0.14 in docker files

- cypress/integration/Admin.feature
- service-admin/src/App/src/Handler/SystemMessageHandler.php
When I try to remove the system message, I am told that a value is required.
Deleting all of the message, followed by clicking ‘set system message’ should, and has previously, work.
Fixes LPAL-175
Reorders logic surrounding setting the system message, adds an additional state when attempting to apply an empty message to system message
> LPAL-175 Admin page: existing system message can't be removed

- service-front/config/autoload/global.php
- service-front/module/Application/src/Model/Service/Session/SessionFactory.php
- service-front/module/Application/tests/Model/Service/Session/SessionFactoryTest.php
The LPAL-60 fix potentially broke session handling, so that
users who had recently logged into the front-end get a
"session expired" message. This could be because we changed the
domain on the lpa cookie, meaning that some users had multiple
cookies with the same name but overlapping domains. In this
situation, the old invalid cookie may have been checked by the
application, causing the session to appear as invalid.
This does suggest a possible bug in the application, as we
should ensure that we are checking the cookie for the correct
domain when deciding whether a session is invalid.
Fixes [LPAL-412](https://opgtransform.atlassian.net/browse/LPAL-412)
Reinstate old code from the sessionmanagerfactory which explicitly sets the session domain.
Change name of session cookie to avoid …
> LPAL-412 Fix for potential session domain issue

- Makefile
- README.md
- cypress/integration/Reusable.feature
- cypress/integration/common/i_can_see.js
- cypress/integration/common/i_visit.js
- service-api/module/Application/src/Model/Service/Applications/Collection.php
- service-api/module/Application/tests/Model/Service/Applications/CollectionTest.php
- service-api/module/Application/tests/Model/Service/Applications/ServiceTest.php
- service-front/module/Application/src/Model/Service/Lpa/Application.php
- service-front/module/Application/tests/Model/Service/Lpa/ApplicationTest.php
- service-front/module/Application/view/application/authenticated/dashboard/index.twig
- service-front/module/Application/view/application/authenticated/dashboard/macros.twig
- service-front/module/Application/view/application/authenticated/lpa/certificate-provider/index.twig
Fixes [LPAL-64]()
Modify the logic which determines whether an LPA application is reusable, pushing it out of the template into the service. Rather than using the LPA status, we now look for metadata to show that the LPA has reached the point where people to notify has been confirmed (i.e. user has clicked on the "Save and continue" button on the people to notify page, regardless of whether they've set people to notify).
This PR also includes some code to enable working on this codebase without AWS credentials.
n/a
> LPAL-64 Enable earlier reuse of LPA details

- .circleci/config.yml
Adds missing requires to build step to fix deployment to master
_Explain how your code addresses the purpose of the change_ 
> LPAL-291 - Adds requires to front_docker_build step

- .circleci/config.yml
Add deployment information that will be useful for developers when debugging issues, and redeployment of the service in case of an error.
Fixes LPAL-443
Add some echo commands which show the relevant deployment info
> LPAL-443 add post release echo to end pipeline job

- service-api/module/Application/src/Model/DataAccess/Postgres/ApplicationData.php
- service-api/module/Application/src/Model/Service/Applications/Service.php
- service-api/module/Application/tests/Model/Service/Applications/ServiceTest.php
Fixes [LPAL-459](https://opgtransform.atlassian.net/browse/LPAL-459)
Use platform-specific quoteValue() method to escape the string
passed into the SQL statement used to query for LPAs by
donor name or LPA ID.
n/a
> LPAL-459 Escape string used to query for LPAs

- terraform/account/certificate.tf
- terraform/account/locals.tf
- terraform/environment/dns.tf
- terraform/environment/locals.tf
- terraform/environment/vpc_data.sources.tf
ACCOUNT LEVEL CHANGE (DEV ONLY AFFECTED).
Align our DNS creation with ADR in Technical Guidance. this is to help clarify which level of environment you are working in.
See Guidance at: https://docs.opg.service.justice.gov.uk/documentation/adrs/adr-002.html#multiple-hosted-zones
Fixes LPAL-445
- DNS names will be in the format `[workspace-name].development.[service-name].opg.service.justice.gov.uk` for dev.
- We've also applied this to the public facing dev one e.g.:  `[workspace-name].development.lastingpowerofattorney.service.gov.uk`
- Cert and Cert Validation Changes
- Preproduction and Production will not need to change as these comply with the ADR.
N/A
> LPAL-445 align dev to ADR on Tech guidance.

- terraform/account/locals.tf
- terraform/account/put_secrets.tf
ACCOUNT LEVEL CHANGE
Add Secrets for perfplat-worker db.
part of the work for LPAL-457
Adds new account level resources which have the postgres account details for the perfplat data.
N/A
> add account level perfplat secrets

- service-api/module/Application/src/Model/DataAccess/Postgres/AbstractBase.php
- service-api/module/Application/src/Model/DataAccess/Postgres/ApplicationData.php
- service-api/module/Application/src/Model/DataAccess/Postgres/DataFactory.php
- service-api/module/Application/src/Model/DataAccess/Postgres/DbWrapper.php
- service-api/module/Application/tests/Model/DataAccess/Postgres/ApplicationDataTest.php
- service-api/module/Application/tests/Model/DataAccess/Postgres/DbWrapperTest.php
- service-api/module/Application/tests/Model/Service/Applications/ServiceTest.php
Fixes [LPAL-462](https://opgtransform.atlassian.net/browse/LPAL-462)
The ApplicationData class was fairly untestable when I first started, so I refactored it to make it more testable, creating a DbWrapper to better encapsulate db access. This could then be injected into the ApplicationData class, and mocked out in tests. The previous inheritance approach didn't give many benefits, as there were few shared methods in the parent class, so composition seemed like a better way to organise things.
I moved most of the code for SELECT queries into the DbWrapper class, including the code to do escaping of values in SELECT statements.
I added tests for DbWrapper->select().
I then added tests for the fetch() and count() methods in ApplicationData, which are simplified by moving a lot of the heavy …
> LPAL-462 ApplicationData unit tests

- .circleci/config.yml
- service-front/module/Application/view/layout/layout.twig
_LPAL-464 add a link just after the Feedback link, to the modernise survey, opens in new tab_
_Minor change to layout.twig to incorporate this just after the feedback link_
> Lpal 464 add (temporary) link to Modernise survey

- .gitignore
- .pre-commit-config.yaml
- README.md
This PR enables pre-commithooks and adds to existing ones to cover php and secrets.
this is to ensure developers/ webops are checking in standardised code.
This is a first attempt and will need tweaking as needed.
Fixes LPAL-478
Add Precommit hooks for:
- PHP
- Secrets scanning
make precommit functional and update readme with install instructions.
- https://pre-commit.com/index.html
- https://pre-commit.com/hooks.html
- https://github.com/digitalpulp/pre-commit-php
- https://github.com/zricethezav/gitleaks
> LPAL-478 Add precommit hooks with instructions

- .github/workflows/gitleaks.yml
- .github/workflows/trufflehog.yml
fetch depth needed to be set (other than 1), and action set to v2 for fetch.
Fixes LPAL-482
- Update checkout action version and fetch depth
- Also update trufflehog to align.
- https://github.com/marketplace/actions/gitleaks
- https://github.com/marketplace/actions/trufflehog-
> LPAL-482 change to fetch depth to reduce false positives

- terraform/account/versions.tf
- terraform/account_ingress/versions.tf
- terraform/email/versions.tf
- terraform/environment/versions.tf
update providers to `required_version = " >=1.0` in terraform.
Fixes LPAL-493
N/A
N/A
> LPAL-493 Update `required_version`

- terraform/account/sns.tf
- terraform/environment/sns.tf
Temporarily remove encryption on SNS topics reserved for cloudtrail based alerts. 
Also remove Elasticache SNS encryption due to silently disassociating it self.
Will follow up with a separate ticket to cover a CMK based approach, where possible.
Fixes LPAL-524 temporarily.
remove encryption (for now).
- CMK needed for cloudwatch alerts (not fixed yet, to follow).
https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-permissions-for-sns-notifications.html
- Elasticache doesn't support encrypted topics, but fails quietly.
https://docs.aws.amazon.com/AmazonElastiCache/latest/mem-ug/ElastiCacheSNS.html
> LPAL-524 SNS encryption doesn't appear to work for certain alerts.

- terraform/environment/rds.tf
To enable autoscale of storage on Make an LPA RDS instance in production. This will allow it to increase to 100Gb, but in 10 Gb increments.
Fixes Low storage event on production.
**NOTE**: We may apply this fix prior to merging main in order to fix the service.
Fixes https://opgtransform.atlassian.net/browse/LPAL-534
adds a `max_allocated_storage` of 100gb, should go up in 5 Gb increments.
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_PIOPS.StorageTypes.html#USER_PIOPS.Autoscaling
https://aws.amazon.com/about-aws/whats-new/2019/06/rds-storage-auto-scaling/
> LPAL-534 - BREAKFIX: make autoscale to 100 Gb available o n RDS DB.

- .github/workflows/trivy-scan.yml
addresses one of the trivy scans failing on service-perfplat folder.
Fixes LPAL-535
remove errant apostrophe.
N/A
> LPAL-535 remove apostrophe

- terraform/account/sns.tf
ACCOUNT LEVEL CHANGE
Add Event subscription and SNS Topic for DB alerts at the account level.
Assists LPAL-500 and other tickets related to RDS Security Hub findings, and 535 which adds cloudwatch monitoring.
See #620 
At account level:
- add `aws_db_event_subscription` 
- add `aws_sns_topic`
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_Events.html
> LPAL-535 precursor work to add topic and event subscription to RDS.

- terraform/account/s3.tf
Security Hub finding fix to S3.
Enforces the use of SSL when accessing s3 buckets. we need to test this works with the PDF cache first before releasing.
Fixes LPAL-497
Adds policy changes to`lpa_pdf_cache` and `access_logs`
see: https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html#s3-5-remediation
> LPAL-497 Add policy to pdf and access logs

- service-api/module/Application/src/Model/DataAccess/Postgres/DbWrapper.php
- service-api/module/Application/tests/Model/DataAccess/Postgres/DbWrapperTest.php
Fixes [LPAL-538](https://opgtransform.atlassian.net/browse/LPAL-538)
Incorrect SQL construction. The perils of using mocks in unit tests combined with missing cypress tests.
n/a
> LPAL-538 Fix LPA search bug

- terraform/environment/rds.tf
reduce disk burst threshold to 50% as 100% too high.
anomalous counts for db connections also adjusted out to 5.
Fixes LPAL-500
adjust module parameter for `disk_burst_balance_too_low_threshold` and `anomaly_band_width`
> LPAL-500 dampen alarm thresholds

- terraform/environment/rds.tf
attempt to reduce some of the chatty alarms a bit.
Fixes LPAL-551
up anomaly value to 10 
up eval periods to 10 x 60 seconds.
N/A
> adjust anomaly and eval periods for RDS alarms

- terraform/account/cloudwatch.tf
- terraform/account/pagerduty.tf
- terraform/account/sns.tf
Add notifications for task failures on ECS.
Fixes LPAL-525
- Set up EventBridge Rule to capture task stopped with  a `TaskFailedToStart` reason
- event target to point at the pager duty ops SNS topic
- used this as a guide: https://github.com/wellcomecollection/platform-infrastructure/pull/246
> LPAL-525 Add Task fail eventbridge rule and publish to ops pagerduty sns

- terraform/account/elasticache.tf
- terraform/environment/rds.tf
We want the maintenance windows to be close to the Wednesday morning Business downtime preferred slot.
Fixes LPAL-557
change elasticache and RDS in production to have maintenance windows from 05:00 -09:00 on Wednesdays.
Also as part of this change: topic publish missed previously. should now be subscribed.
N/A
> LPAL-557 move maint windows to wednesday mornings for RDS and Elasticache

- terraform/account/put_secrets.tf
- terraform/environment/terraform.tfvars.json
to add a kms key for RDS Cross region snapshots.
Supports LPAL-556
Add CMK for encrypting snapshots for cross region replication.
Unfortunately the Terraform AWS provider currently doesn't support Cross Region Replication, so this will have to be done manually.
this [issue](https://github.com/hashicorp/terraform-provider-aws/issues/20606) has been raised on the providers github repo.
Also enable snapshot retention to 2 days for testing purposes in preproduction. We'll remove this later, once satisfied it works.
Cross-region snapshots for RDS: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_ReplicateBackups.html
> LPAL-556 add a secret for cross region snapshot encryption

- terraform/region/modules/region/elasticache.tf
- terraform/region/modules/region/s3.tf
- terraform/region/modules/region/variables.tf
- terraform/region/terraform.tf
- terraform/region/variables.tf
To add definitions for region based S3 Buckets.
Fixes LPAL-598
Takes a copy of existing account based buckets and creates new ones which are region ready.
Additional items: 
- Use Elasticache 6.x on new resources.
- Add descriptions 
- Some minor clean up.
Still not CI Based. in a later ticket.
N/A
> Lpal 598 rebuild s3 region based buckets

- terraform/environment/sns.tf
remove SNS default key on Cloudwatch to Pagerduty SNS topics on environment level resources. it was prevented firing of alarms by this error:
```
Failed to execute action arn:aws:sns:eu-west-1:xxxxxxxxxx:CloudWatch-to-PagerDuty-production-Ops. Received error: "null (Service: AWSKMS; Status Code: 400; Error Code: AccessDeniedException; Request ID:some-request-uuid; Proxy: null)"
```
Fixes LPAL-620, and should reinstate environment level ops notifications.
- remove and ignore the encryption on tfsec 
- I have created a further ticket to fix to use a CMK: see LPAL-619
https://aws.amazon.com/premiumsupport/knowledge-center/cloudwatch-receive-sns-for-alarm-trigger/
> LPAL-620 remove standard kms key use on sns topic as is not usable in cloudwatch

- cypress/Dockerfile
- cypress/integration/ApplicantPF.feature
- cypress/plugins/index.js
- cypress/support/index.js
_Recent changes to cypress flags to speed it up, have removed some feedback when tests fail. Introduce the failed logs plugin to give this feedback on the command line_
Fixes LPAL-626
_Install the necessary plugin_ 
Learning: 
- Plugin: https://github.com/bahmutov/cypress-failed-log
> LPAL-626 cypress tests add failed logs plugin.

- service-api/docker/app/Dockerfile
Pin  PHP to alpine3.14 as 3.15 broke postgres libraries
Fixes LPAL-631
Update Dockerfile.
N/A
> LPAL-631: pin to 3.14 alpine linux for PHP.

- terraform/region/modules/region/cloudwatch.tf
To adjust the alert from 50MBits, to 95MBits. 
The current alert is triggering too much and the service is not affected at this level. The normal range is 20 to 90 MBits.
Fixes LPAL-652
Change CloudWatch alarm to new value.
N/A
> LPAL-652 elasticache alert for high swap use to 95 MBits

- cypress/integration/CorrespondentPFClone.feature
_LPAL-650 add extra testing to cover gaps revealed during UAT of PHP8 upgrade_
_Add extra lines to CorrespondentPFClone feature file. Now tests with Certificate Provider before Attorney, more checking of exact text shown on page as result_
> LPAL-650 improve coverage of Change Correspondent feature

- .circleci/config.yml
- .gitignore
- docker-compose.yml
- service-admin/.dockerignore
- service-admin/docker/app/Dockerfile
- service-api/.dockerignore
- service-api/docker/app/Dockerfile
- service-front/.dockerignore
- service-front/docker/app/Dockerfile
- service-pdf/.dockerignore
- service-pdf/docker/app/Dockerfile
_LPAL-646 get the debugger working again and do a few things to try to slim down building and running locally_
- Config for debug is now set to what is required for xdebug 3, and debugger works again inside phpstorm. 
- We no longer install debugger by default, we now depend on ENABLE_DEBUG being set. We only want the debugger when running locally, not in CI, and its a potential security risk if installed on live even if not enabled.
- CircleCI therefore no longer turns on debugger to run unit tests. These run fine without the debugger. Perhaps in the past there was a dependency here, but no longer needed.
- I tried just installing the debugger during build phase if required, then optionally enabling it just as the container runs up, just as we currently do prior to this PR (not currently …
> LPAL 646 fix debugging and attempt to improve performance running locally

- .circleci/config.yml
- scripts/pipeline/check_ecr_scan_results/aws_ecr_scan_results.py
- scripts/pipeline/check_ecr_scan_results/templates/finding.j2
- scripts/pipeline/check_ecr_scan_results/templates/header.j2
Fixes a fault with ECR Scan after AWS inspector Upgrade. 
Findings are different.
Fixes LPAL-656
- fix Python script.
- fix templates as some info no longer easy to get.
> LPAL-656 Adjust ECR Scan reports and script to be Inspector2 compatible

- service-pdf/composer.json
- service-pdf/composer.lock
_Upgrade to more secure version of php-shellcommand_
Fixes LPAL-657
_Force version in composer.json_
> LPAL-657 fix php-shellcommand to be latest 1.6.4 instead of 1.0.2

- terraform/environment/modules/environment/ecs_cluster.tf
- terraform/environment/modules/environment/shared_data_sources.tf
to make the MRK data source available to the environment level.
part of LPAL-603 work
- Add datasource for MRK
- Add relevant permissions
this will make it smoother to move the secrets to  this key.
N/A
> Lpal 603 make MRK available to the environment level  

- terraform/region/secrets.tf
- terraform/region/secrets_move.sh
make secretes multi region part 1 - MRK assignment.
Fixes LPAL-603
Assign MRK to the secrets so we can then make the secrets cross region replicated.
Required some state moves - attached to this PR.
> LPAL-603 update secrets to use MRK.

- service-front/module/Application/view/application/general/forgot-password/email-sent.twig
_Content change on password reset page to remove no longer wanted paragraph_
_twig tweak to remove 1 para and add 1 word to last para _
> LPAL-554 remove no longer wanted text from password reset page

- cypress/integration/Password.feature
- cypress/integration/common/password.js
- service-front/content/guidance/People_Correspondent.md
- service-front/module/Application/view/application/authenticated/lpa/status/index.twig
- service-front/module/Application/view/application/general/forgot-password/partials/reset-password-error-summary.twig
_LPAL 553 to re-order the waiting msg, LPAL-669 to remove covid-related link from correspondent help page, LPAL-648 to fix issue with password mismatch message_
_Minor tweaks to relevant twig and md files. Improved cypress test to test a mismatch in forgot password link too_
> Lpal 553 waiting msg, LPAL-669 remove covid link, LPAL-648 fix password mismatch msg for forgot password

- terraform/region/kms.tf
Adds a multi region key for use with encryption of automated backup to another region
Supports LPAL-681
Add MRK to support automated backup to another region. 
Currently Terraform does not support cross region replication of RDS.  we will have to do this outside of the codebase.
however this issue https://github.com/hashicorp/terraform-provider-aws/issues/16708 is in flight and on the current quarter's roadmap, so should be available soon.
see https://github.com/hashicorp/terraform-provider-aws/blob/main/ROADMAP.md for details.
> LPAL-681 add db snapshot cross region encryption key

- service-front/module/Application/src/Model/Service/Payment/Helper/LpaIdHelper.php
- service-front/module/Application/tests/Model/Service/Payment/Helper/LpaIdHelperTest.php
To support work to be done in Sirius migrations, the the time stamp element of the pay reference number is to be removed from the fees page.
Only the A-ref is to be visible here. (The A-ref is to remain visible next to the barcode)
Fixes LPAL-674
_Explain how your code addresses the purpose of the change_ 
<s>   I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant</s>
<s>  I have added mandatory tags to terraformed resources, where possible</s>
<s>  If I added a package.json or composer.json, I also made sure this is included in the script in `.github/workflows/dependabot-update.yml`</s>
> LPAL-674 Remove timestamp element of pay ref on fees page of LPA

- cypress/integration/RepeatApplicationPF.feature
- service-front/module/Application/src/Form/Lpa/RepeatApplicationForm.php
- service-front/module/Application/tests/Form/Lpa/RepeatApplicationFormTest.php
- service-front/module/Application/view/application/authenticated/lpa/repeat-application/index.twig
_Case number on repeat application needs to be restricted to 12 chars no more no less_
_Minor change to validator in php, and formErrorExchange in twig, with addition to cypress test. Change existing tests which only had 8 chars which is invalid 😂  _
> LAPL-675 restrict case number on repeat application to 12 chars

- terraform/region/modules/region/kms.tf
to provide a key for cloudwatch use at the region level, to support LPAL-677
Fixes LPAL-677
add a key and alias.
> create kms key for cloudwatch at region level

- terraform/region/modules/region/kms.tf
Add a kms resource policy to allow encryption and decryption rights for new encryption kms key
Allows:
- root key permissions
- encryption decryption of logs/ events
- Key administration alowed for breakglass
assists LPAL-677
Add a policy to allow use of the KMS key in the terraform
Key policies: https://docs.aws.amazon.com/kms/latest/developerguide/key-policies.html
> LPAL-677 add policy fo cloudwatch encryption key

- README.md
To add badge for repo readme that shows compliance with MOJ Repo standards.
Fixes LPAL-719
Note we also fixed the repo in org infra under a separate PR: https://github.com/ministryofjustice/opg-org-infra/pull/1465
add badge to readme.
See https://github.com/ministryofjustice/github-repository-standards
> LPAL-719 update readme to include repo standards badge

- docs/runbooks/cloud9/cloud9_init.sh
Update the tooling for Cloud9 instances
Fixes LPAL-721
- use amazon-linux-extras
- use PSQL10
https://aws.amazon.com/premiumsupport/knowledge-center/ec2-install-extras-library-software/
> LPAL-721 update script to use amazon-linux-extras and psql10

- service-admin/docker/web/Dockerfile
- service-front/docker/app/Dockerfile
- service-front/docker/web/Dockerfile
Update Service front to execute as non root on it's containers
Fixes LPAL-725
Follow on from LPAL-723 and LPAL-725, update web and app containers.
See #873  and #878 for further details.
> LPAL-725 front docker as non root

- Makefile
- service-pdf/docker/app/Dockerfile
Following on from Admin , API and Front, update so that pdf container runs as non root.
Fixes LPAL-727
Same aproach as LPAL-723, LPAL-725, LPAL-726 as the changes are similar.
added an additional PDF testing make entry.
see PRS:
- #873 
- #878 
- #886
> LPAL-727 update pdf container to exec as non root

- service-front/docker/app/Dockerfile
- service-pdf/docker/app/Dockerfile
Fix composer versions to a fixed version 2.2.12 as per CVE mentioned in LPAL-734.
Fixes LPAL-734
update PDF and Front  2.1.11 -> 2.2.12 
https://blog.packagist.com/cve-2022-24828-composer-command-injection-vulnerability/
> LPAL-734 update to 2.2.12 as per CVE

- docs/architecture/0009-change-internal-namespace.md
- terraform/environment/modules/environment/dns.tf
- terraform/region/modules/region/dns_firewall.tf
Following on from discussions with the Community Of Practice regarding internally named domains, Adjust to match better naming convention. See ADR 0009 (updated in this PR) for details of the amendments
Fixes LPAL-730
- Amend ADR 0009
- Adjust internal DNS Namespace with new convention for Dev only
- Update DNS Resolver rule to cover changes
Note - there is a follow up ticket which will roll these changes through to production, but these require a down time slot.
- Multiline ternaries in Terraform require brackets!
> LPAL-730 adjust ADR for internal domains

- terraform/region/modules/region/sns.tf
We need to move the DB events subscription to the region level, as this needs to be supported in all regions in case of a DR Situation.
Fixes LPAL-709 (partially) 
- will follow up with a second  PR to remove at account level.
- create region level events subscription
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_Events.html
> LPAL-709 create an events subscription at region level

- service-front/module/Application/view/application/general/feedback/index.twig
Service feedback page is to be amended so users happy to take part in UR can be identified ([LPAL-697](https://opgtransform.atlassian.net/browse/LPAL-697)).
- 1st para : remove 2nd sentence starting ' If you’re happy…' 
- Below comments free text box:  add ‘If you’re happy to take part in research about this service, please leave your preferred contact details.’
- Remove ‘(optional)' from ‘Your email address’ and ‘Your phone number’. However, both ARE optional - the should be able to submit the form with either both, one or neither or these fields completed. 
(This task is to follow the release of survey link being removed from the homepage, which it now has been)
Removes and adds content as specified
> LPAL-697 - Update content on feedback form

- Makefile
- cypress/integration/SignupAndChangeDetails.feature
- cypress/integration/UserPersonalDetails.feature
- cypress/integration/common/activation_email.js
- cypress/integration/common/i_change_details.js
- cypress/integration/common/i_log_in.js
- cypress/integration/common/i_sign_up.js
- cypress/integration/common/i_visit.js
- cypress/integration/common/password.js
- service-front/module/Application/src/Model/Service/Lpa/Application.php
- service-front/module/Application/src/View/Helper/AccountInfo.php
- service-front/module/Application/view/application/authenticated/change-email-address/partials/index-error-summary.twig
- service-front/module/Application/view/application/general/register/partials/index-error-summary.twig
- service-front/module/Application/view/application/partials/confirm-email-error-summary.twig
Fixes [LPAL-651]()
* Prevent RuntimeError breaking template rendering by instead returning empty data object
* Modify cypress scripts so we can sign up multiple users during test suite run
* Add test for mismatched password change and mismatched email change
I didn't get to the bottom of why we were getting a runtime error when trying to get the LPA applications for the current logged-in user. However, I could see it happening. It's generally a bad idea to do this, though: better to return the equivalent of a [null object](https://en.wikipedia.org/wiki/Null_object_pattern) instead of breaking the template with an unexpected exception because an HTTP request failed. Also, shouldn't really be doing HTTP requests from view helpers, but that's another issue.
> LPAL-651 Prevent raw 500 page when newly-signed-up user changes email/password 

- terraform/account/pagerduty.tf
- terraform/account/sns.tf
Remove redundant account level subscription for DB alerts. 
Fixes LPAL-709
update account level terraform to remove entries no longer required.
N/A
> LPAL-709 remove account level rds subscription

- docs/runbooks/pager_duty_custom_event_handler/development_custom_event.js
- docs/runbooks/pager_duty_custom_event_handler/preproduction_custom_event.js
- docs/runbooks/pager_duty_custom_event_handler/production_custom_event.js
- docs/runbooks/pager_duty_custom_event_handler/readme.md
Add a runbook and code snippets examples for stting up PagerDuty DB alerts
Fixes LPAL-739
- Add Readme
- Add 3 code snippets
This is to capture this manual process, as it will be needed for future DR tests.
> LPAL-739 add runbook for custom event transform db

- .circleci/config.yml
We run a daily key rotation at a similar time to this used to run, so change this to avoid failures
> Change the time to 5am

- docs/runbooks/terraform_state_locks.md
To provide easy-to-follow instructions on removing the dev state lock which keeps blocking our builds.
Update the docs.
Some terraform stuff
> Add step-by-step instructions on removing dev state lock

- terraform/environment/modules/environment/ecs_hibernation.tf
As per amy's request, dev environment scaling set to scale down much later. this is a temporary move.
Fixes LPAL-749
update cron settings for autoscaling module.
> LPAL-749 hibernation extended to midnight bst

- cypress/integration/Statuses.feature
- cypress/integration/common/statuses.js
- service-api/module/Application/src/Controller/StatusController.php
- service-api/module/Application/src/Model/Service/ProcessingStatus/Service.php
- service-api/module/Application/tests/Controller/Version2/Lpa/StatusControllerTest.php
- service-front/module/Application/src/Controller/Authenticated/Lpa/StatusController.php
- service-front/module/Application/src/Model/Service/Lpa/Application.php
- service-front/module/Application/view/application/authenticated/dashboard/index.twig
- service-front/module/Application/view/application/authenticated/lpa/status/index.twig
- service-gateway-mock/README.md
- service-gateway-mock/nginx.conf
- service-gateway-mock/swagger-examples.yaml
[LPAL-550](https://opgtransform.atlassian.net/browse/LPAL-550)
* Add additional logging to track down issue (then remove it again).
* Fix logic which was preventing correct status being shown.
This was difficult to find as the error only triggers when the status is first viewed at a point when the LPA is in a non-waiting status, then is viewed again after the LPA application has been removed from Sirius (giving us a 410 response). 
The problem arose because the initial valid response was cached into our db. Then, when the 410 response was later fetched, our logic prevented it from overriding the cached response (as 400 codes were not allowed to override the cache, being treated as `found=>false`).
Also found another bug in opg-data-lpa where statusDate was not set on some responses when …
> LPAL-550 LPA deletion status

- cypress/integration/InstructionsPreferencesHW.feature
- cypress/integration/InstructionsPreferencesPF.feature
temporarily disable instructions and preferences visibility check prior to click. there is a Timeout issuecwithis specific test and these lines that seems to be introduced by a later version of cypress pulling chrome or electron.
this is for H/W and P/F.
Does not affect the functionality.
Fixes LPAL-807
comment lines out in 2 test specs
this will be followed on by a further ticket to fix the issue that is holding the builds because of the element timeout issue
> LPAL-807 comment lines for instructions and prefs.

- cypress/integration/InstructionsPreferencesHW.feature
- cypress/integration/InstructionsPreferencesPF.feature
- cypress/integration/common/i_can_find.js
[LPAL-809](https://opgtransform.atlassian.net/browse/LPAL-809)
See issue for context. Main problem is that Chrome and Electron treat visibility of elements within a `<details>` element differently.
Instead of .should('not.be.visible')/should('be.visible'),
use Cypress.dom.isHidden()/Cypress.dom.isVisible()
to test visibility or not of DOM elements.
This does a more precise job of checking whether an element is
really visible, beyond just looking at its CSS or DOM properties.
More about DOM visibility and how to test in cypress.
> LPAL-809 Use lower-level Cypress.dom methods for visibility tests

- service-admin/composer.lock
- service-api/composer.lock
- service-front/composer.lock
- service-pdf/composer.lock
- tests/composer.lock
Rather than 5 separate PRs generated by dependabot (minor security fix), rolled up this security update into one branch.
Fix for guzzle/guzzlehttp security issues: 
* version 7.4.3 - https://github.com/guzzle/guzzle/blob/HEAD/CHANGELOG.md#743---2022-05-25
* version 6.5.6 - https://github.com/guzzle/guzzle/blob/6.5/CHANGELOG.md#656---2022-05-25
Fixes these dependabot alerts:
* https://github.com/ministryofjustice/opg-lpa/security/dependabot/23
* https://github.com/ministryofjustice/opg-lpa/security/dependabot/24
* https://github.com/ministryofjustice/opg-lpa/security/dependabot/25
* https://github.com/ministryofjustice/opg-lpa/security/dependabot/26
* https://github.com/ministryofjustice/opg-lpa/security/dependabot/27
Fixes [LPAL-810](https://opgtransform.atlassian.net/browse/LPAL-810)
n/a …
> LPAL-810 Roll-up of guzzle/guzzlehttp composer updates

- terraform/environment/terraform.tfvars.json
to enable WAF in dev to test for issues with the Shield Advanced Integration. this sets up a `aws_wafv2_web_acl_association` with front and admin load balancers.
Enable Waf var in terraform, which enables the association for the load balancers.
https://docs.aws.amazon.com/waf/latest/developerguide/shield-policies.html
> LPAL-813 enable WAF in Dev

- terraform/environment/modules/environment/cloudwatch_alarms.tf
To support the shield advanced integration, add alarms for DDoS detection, which will come from this service.
Fixes LPAL-816
Add 2 alarms, based on Use an LPA PR: https://github.com/ministryofjustice/opg-use-an-lpa/pull/1549
N/A
> LPAL-816 add shield DDoS alarms

- terraform/environment/modules/environment/dns.tf
To enable the internal namespace changes from #894 
Fixes LPAL-720
change local var to calculate dns convention to exclude `production` rather than being `development` only. There will be a follow on DNS change for `production` which will require downtime, to be scheduled. this will fire the preprod replace check as this replaces the ECS service clusters
N/A
> LPAL-720 change internal dns in preprod

- terraform/environment/modules/environment/dns.tf
This reverts commit ecd0d92d84e02ab4e68ca352201d7ff9a079e1e5.
So service discovery namespaces are not destroying properly on an existing environment.
This needs further work on it, so i am reverting to unblock the Path to Live.
Fixes LPAL-720
revert commit
We hit a snag which is listed in this issue.
https://github.com/hashicorp/terraform-provider-aws/issues/4853
seems to have regressed in V4 of the aws provider. So will investigate what to do next.
> LPAL-720 Revert "LPAL-720 change internal dns in preprod (#957)"

- terraform/environment/modules/environment/cloudwatch_alarms.tf
Spotted an issue with naming of DDoS alarms. This fixes it.
Fixes LPAL-816
correct names
Spotted in another pr apply.
> Fix copy paste names

- terraform/environment/modules/environment/cloudwatch_alarms.tf
- terraform/environment/modules/environment/dns.tf
- terraform/environment/modules/environment/ecs_api.tf
- terraform/environment/modules/rds_cross_region_backup/main.tf
Create a new Service Discovery Namespace and Service for the Service API to use instead, which uses the new canonical naming convention as agreed in ADR 0008 on this repo. This will be implemented on environments in dev and preproduction first before being rolled out in a maintenance slot for production.
Fixes LPAL-720
- create new service discovery namespace, using the agreed format
- keep existing for production use
- create new service discovery service using that namespace
- attach correct service discovery service arn to the api ECS Service, using a local selection based on environment
We will remove the older namespace and service later on, once implemented in production.
Note - i've update further the DDoS Alarms to be environment specific. …
> LPAL-720 service discovery dns rework, better fix.

- terraform/environment/modules/environment/ecs_api.tf
- terraform/environment/modules/environment/ecs_feedbackdb.tf
- terraform/environment/modules/environment/ecs_front.tf
- terraform/environment/modules/environment/ecs_pdf.tf
- terraform/environment/modules/environment/ecs_seeding.tf
- terraform/environment/modules/environment/load_balancer_admin.tf
- terraform/environment/modules/environment/load_balancer_front.tf
- terraform/environment/modules/environment/rds.tf
Add descriptions to Security Group Rules 
Fixes LPAL-724
Add a description attribute to every aws_security_group_rule resource
aws_security_group's description attribute is immutable and requires destroy / create but the aws_security_group_rule description does not.
> LPAL-724 Add descriptions to aws_security_group_rule Terraform resources

- terraform/account/pagerduty.tf
- terraform/environment/modules/environment/pagerduty.tf
- terraform/region/modules/region/pagerduty.tf
This reverts commit dc371a0064637f04bf473220d49d58f992284958.
Revert previous Workaround  for pagerduty
Fixes LPAL-825
Revert merged commit to restore to correct approach.
N/A
> LPAL-825 Revert "Lpal 824 Workaround for PagerDuty API error (#967)"

- terraform/email/email.tf
Block / ignore public ACLs on the mail S3 bucket so that public policies cannot be accidentally added in the future.
Fixes LPAL-724
Add a aws_s3_bucket_public_access_block resource to explicitly block and ignore new public ACLs.
Learned that SES mail can be stored in S3.
> LPAL-724: Add public access block to mail s3 bucket

- terraform/region/terraform.tfvars.json
To explicitly allow DNS lookups of the Notify CNAMEs on the DNS firewall
Fixes LPAL-819
Add the record of the AWS ELB (currently used around 5% of the time) and the new CloudFront record.
n/a
> LPAL 819: Add Notify CNAMEs to DNS firewall

- terraform/account/workspace_cleanup.tf
- terraform/environment/modules/environment/dynamo_db.tf
Add extra ignore for DynamoDB encryption
Fixes LPAL-724
Add additional tfsec ignore for DynamoDB tables not requiring encryption.
n/a
> LPAL 724 Correct ignores on dynamodb encryption

- terraform/environment/terraform.tfvars.json
- terraform/region/modules/region/certificate.tf
- terraform/region/modules/region/locals.tf
To Move account level cert definitions into region code, to allow region level Certificates. 
the process requires a bunch of imports and removals. Do not merge before completing approach below on preproduction and production.
Fixes LPAL-877
the script is as follows (sensitive info redacted), each step is run individually for safety:
``` bash
#go to account level folder
cd terraform/account
#in account level init the workspace
export TF_WORKSPACE=<account name>
export TF_VAR_default_role=breakglass
aws-vault exec identity -- terraform init
#extract cert id's
aws-vault exec identity -- terraform show -json | jq '.values[].resources[] | select (.address | contains("cert")) | "aws-vault exec identity -- terraform import '"'"'module.eu-west-1." + .address + "'"'"' '"'"'"+ .values.id + …
```
> LPAL-877 move certs to region level

- terraform/account/cloudwatch.tf
- terraform/account/iam.tf
- terraform/account/s3.tf
- terraform/account/sns.tf
- terraform/account/terraform.tf
- terraform/account/workspace_cleanup.tf
Add provider-level default tags for account Terraform
Fixes LPAL-859
Move default tags to provider block and remove merge function usage where no longer necessary. Limited to accounts terraform directory.
n/a
> LPAL-859: Use provider-level default tags for account

- service-front/assets/sass/extensions/elements/_forms.scss
- service-front/assets/sass/patterns/_form-popup.scss
[LPAL-885](https://opgtransform.atlassian.net/browse/LPAL-885)
Judicious margin adjustment and overflow change to make the outline visible around date entry inputs.
n/a
> LPAL-885 Reveal outline around date entry fields

- .github/workflows/tfsec-pr-commenter.yml
Re-add the TFSEC Commenter to the repo. the idea is that it will create comments for TFSec violations on terraform.
Fixes LPAL-872
Add a github action 
https://github.com/aquasecurity/tfsec-pr-commenter-action
> LPAL-872 Add tfsec commenter to Github Actions

- .idea/php.xml
- service-front/docker/app/Dockerfile
_fix xdebug locally_
_Removal of build dependencies needs to happen later in dockerfile than when xdebug is installed_
> LPAL-889 fix debugger

- terraform/region/modules/region/certificate.tf
- terraform/region/modules/region/cloudwatch.tf
- terraform/region/modules/region/dns_firewall.tf
- terraform/region/modules/region/elasticache.tf
- terraform/region/modules/region/kms.tf
- terraform/region/modules/region/s3.tf
- terraform/region/modules/region/sns.tf
- terraform/region/modules/region/subnet.tf
- terraform/region/modules/region/vpc.tf
- terraform/region/modules/region/vpc_flow_logs.tf
- terraform/region/terraform.tf
Use provider-level `default_tags` block instead instead of duplicating merging default_tags on each resource. Region level only.
Fixes LPAL-859
Removes unnecessary merge function calls and use default_tags in the provider block.
n/a
> LPAL-859 New default_tags in region

- service-front/module/Application/view/application/authenticated/dashboard/macros.twig
[LPAL-886](https://opgtransform.atlassian.net/browse/LPAL-886)
Use the same styling as main action buttons (white text on green) for the View LPA buttons in the dashboard.
n/a
> LPAL-886 Restyle "View LPA" button to improve contrast

- terraform/region/modules/region/s3.tf
For some reason dev ephemerals were hitting 400 error when creating load balancers with this key in place. 
Fixes LPAL-859 in dev
remove CMK for sse encryption.
> LPAL-859 remove CMK - seems new envs can't work with it.

- terraform/environment/modules/environment/autoscaling.tf
- terraform/environment/modules/environment/cloudwatch_alarms.tf
- terraform/environment/modules/environment/cloudwatch_logs.tf
- terraform/environment/modules/environment/dynamo_db.tf
- terraform/environment/modules/environment/ecs_admin.tf
- terraform/environment/modules/environment/ecs_api.tf
- terraform/environment/modules/environment/ecs_api_cron.tf
- terraform/environment/modules/environment/ecs_cluster.tf
- terraform/environment/modules/environment/ecs_feedbackdb.tf
- terraform/environment/modules/environment/ecs_front.tf
- terraform/environment/modules/environment/ecs_pdf.tf
- terraform/environment/modules/environment/ecs_seeding.tf
- terraform/environment/modules/environment/lambda_functions.tf
- terraform/environment/modules/environment/load_balancer_admin.tf
- terraform/environment/modules/environment/load_balancer_front.tf
- terraform/environment/modules/environment/rds.tf
- terraform/environment/modules/environment/resource_group.tf
- terraform/environment/modules/environment/sns.tf
- terraform/environment/modules/environment/sqs.tf
- terraform/environment/terraform.tf
Use default_tags block in AWS TF Provider
Fixes LPAL-859
Removes unnecessary merge function calls and replaces with default_tags block in the AWS provider config
n/a
* [] I have added mandatory tags to terraformed resources, where possible
> LPAL-859 Use default_tags block in TF provider

- terraform/email/credentials.tf
- terraform/email/email.tf
Use default_tags in email provider block
Fixes LPAL-859
Adjust email terraform to use default_tags block
n/a
> LPAL-859 Add default_tags block in TF AWS provider

- .github/workflows/tfsec-pr-commenter.yml
- terraform/environment/modules/environment/lambda_functions.tf
- terraform/environment/modules/environment/modules/lambda_function/main.tf
- terraform/environment/modules/environment/modules/lambda_function/variables.tf
Add log retention control to Lambda module
Fixes LPAL-666
- update module to take `log_retention_in_days` setting from the `terraform.tfvars.json` file.
Still cannot make the setting of other insight logs variable.
> LPAL-666 add lambda log retention control

- terraform/environment/modules/environment/modules/aurora/main.tf
AWS has since Friday placed an enforcement on the Aurora serverless engine version, which has stopped our dev CI in it's tracks. This change fixes that issue and by doing so means we actually specify the engine version in serverless, which was missed previously.
Fixes LPAL-917
Add `engine_version` in. to the serverless db definition, which was assumed to be there anyway.
N/A
> LPAL-917 Fix suddenly enforced engine version

- terraform/email/email.tf
- terraform/environment/modules/environment/modules/lambda_function/main.tf
- terraform/region/modules/region/sns.tf
Ignore the remaining security alerts which can't yet be fixed.
Fixes LPAL-724
Add ignore comments for tfsec.
n/a
> LPAL-724 Ignore (for now) remaining alerts

- cypress/e2e/common/i_can_see.js
- service-front/module/Application/view/application/authenticated/lpa/date-check/index.twig
This PR is a duplicate of an already approved PR. The difference is that this is being reopened against the feature branch [lpal-892-date-check-c-sheet-feature](https://github.com/ministryofjustice/opg-lpa/pull/1053), as it needs to be released alongside the other tasks in the epic [LPAL-892](https://opgtransform.atlassian.net/browse/LPAL-892).
This changes the wording in the 'Check Signatures' tool so that when the donor can't sign (this generates continuation sheet 3), it refers to 'The person signing on behalf of the donor', rather than 'The donor'.
[LPAL-875](https://opgtransform.atlassian.net/browse/LPAL-875)
> LPAL-875 Change wording when the donor can't sign

- terraform/region/secrets.tf
Allow the Feedback CI user to read the Feedback Secret
Fixes LPAL-919
As the Secret currently is manually created, the code performs a data lookup for the `opg-flask-api-token`. A `aws_secretsmanager_secret_policy` is then created referencing the ARN of the Secret.
n/a
> LPAL-919 Allow feedback ci flask secret access

- terraform/region/secrets.tf
Fix path to live pipeline
Fixes LPAL-919
Makes data lookups conditional on the environment not being production
n/a
> LPAL-919 Make non-prod data lookups conditional

- docker-compose.yml
_image names for feedbackdb and feedbackapp were duplicated. Possibly a bad merge happened. This fixes it_
_fix docker-compose file_
> fix image names

- terraform/account/cloudwatch.tf
- terraform/account/s3.tf
- terraform/account/sns.tf
- terraform/account/workspace_cleanup.tf
- terraform/email/email.tf
- terraform/environment/modules/environment/cloudwatch_logs.tf
- terraform/environment/modules/environment/dynamo_db.tf
- terraform/environment/modules/environment/ecs_admin.tf
- terraform/environment/modules/environment/ecs_api.tf
- terraform/environment/modules/environment/ecs_cluster.tf
- terraform/environment/modules/environment/ecs_feedbackdb.tf
- terraform/environment/modules/environment/ecs_front.tf
- terraform/environment/modules/environment/ecs_pdf.tf
- terraform/environment/modules/environment/ecs_seeding.tf
- terraform/environment/modules/environment/load_balancer_admin.tf
- terraform/environment/modules/environment/load_balancer_front.tf
- terraform/environment/modules/environment/modules/lambda_function/main.tf
- terraform/region/modules/region/elasticache.tf
- terraform/region/modules/region/s3.tf
- terraform/region/modules/region/sns.tf
- terraform/region/modules/region/vpc.tf
- terraform/region/modules/region/vpc_flow_logs.tf
tfsec is no longer ignoring rules by their AWSXXX ID. 
Fixes LPAL-949
Change all ignore rules to be rule names instead of legacy tfsec IDs.
n/a
> LPAL-949 tfsec ignore rule names instead of legacy id

- terraform/region/modules/region/waf.tf
Block illegitimate requests to Make an LPA web service.
Fixes LPAL-933
Change the AWS managed CommonRuleSet from Counting bad requests to blocking bad requests. `NoUserAgent_HEADER` is intentionally still allowed as there are a lot of seemingly legitimate requests with no user agent header set.
N/A
> LPAL-933: Remove count override for CommonRuleSet

- cypress/e2e/DateCheck.feature
- cypress/e2e/common/i_can_see.js
- service-front/module/Application/src/Controller/Authenticated/Lpa/DateCheckController.php
- service-front/module/Application/src/View/DateCheckViewModelHelper.php
- service-front/module/Application/tests/View/DateCheckViewModelHelperTest.php
- service-front/module/Application/view/application/authenticated/lpa/date-check/index.twig
[LPAL-921](https://opgtransform.atlassian.net/browse/LPAL-921)
Amend guidance in Check Signatures tool when continuation sheet 3 applies to reflect that it is not the donor themselves who would be signing, but the person who would sign on their behalf.
> LPAL-921 Update CS guidance when donor can't sign

- cypress/e2e/DateCheck.feature
- cypress/e2e/common/i_can_see.js
- service-front/module/Application/src/View/DateCheckViewModelHelper.php
- service-front/module/Application/view/application/authenticated/lpa/date-check/index.twig
[LPAL-890](https://opgtransform.atlassian.net/browse/LPAL-890)
Change heading and text of applicant in the 'Check signatures' tool when the applicant is the donor and the donor cannot sign to say 'The person signing on behalf of the donor'.
[LPAL-891](https://opgtransform.atlassian.net/browse/LPAL-891)
Change validation error messages when the donor cannot sign, and also when the applicant is the donor and the donor cannot sign.
> LPAL-890 and LPAL-891 donor cant sign related messaging

- terraform/region/terraform.tfvars.json
Correct DNS firewall domain names
Fixes LPAL-955
Add terminating dot to end of cloudfront.net DNS name in variables file.
> LPAL-955 Correct DNS firewall domain names

- .circleci/config.yml
- .github/workflows/workflow_terraform_environment_cleanup.yml
Move Cleanup PR workspace cron job to Github Actions
Fixes LPAL-956
Remove Cleanup PR workspace cronjob from circle CI and add equivalent commands to Github Actions
> LPAL-956 Move Cleanup PR workspaces cron to Github Actions

- scripts/pipeline/workspace_cleanup/workspace_cleanup.sh
Fix workspace cleanup cronjob
Fixes LPAL-978
The workspace_cleanup.sh uses several bashisms but the shebang calls for sh. This replaces the shebang to use bash instead.
> LPAL-978 Use bash in workspace_cleanup

- docker-compose.yml
- terraform/environment/modules/environment/rds.tf
- terraform/environment/modules/environment/variables.tf
- terraform/environment/terraform.tfvars.json
- terraform/environment/variables.tf
[LPAL-976](https://opgtransform.atlassian.net/browse/LPAL-976)
* Upgrade docker-compose.yml to use postgresql v13.6.
* Clean out local volumes relating to postgres and existing postgres images.
* Run `make cypress-local` to run the main user journeys.
* Run `make cypress-open` and run other UI tests manually.
n/a
> LPAL-976 Upgrade local docker stack to use postgresql 13.6

- terraform/environment/terraform.tfvars.json
Reflect manual changes made to upgrade the production database to use PG 13.6 in Terraform.
Fixes LPAL-854
Manual changes to be made before this is merged:
1) Redirect users to maintenance;
2) Ensure there are no connections to the Postgres instance (SELECT * FROM pg_stat_activity; - unsure how reliable RDS stats are);
3) Scale down the API service to zero;
4) Manually set default_transaction_read_only to true in PG13 AND PG10 parameter groups;
5) Take a manual snapshot of the instance;
6) Manually upgrade the instance type from db.m3.medium to db.m5.large;
7) Manually upgrade the Postgres engine from 10.18 to 13.4;
8) Manually upgrade the Postgres engine from 13.4 to 13.6;
9) Run VACUUM FULL ANALYZE;
10) Set default_transactions_read_only to false in PG13 and PG10 parameter groups;
11) …
> LPAL-854 Upgrade production to Postgres 13

- .circleci/config.yml
Resolve issue with Docker Orb by updating it
Fixes LPAL-943
Update docker orb version in CircleCI pipeline
https://github.com/CircleCI-Public/docker-orb/issues/154
> LPAL-943 Update CircleCI docker orb

- terraform/environment/modules/environment/ecs_admin.tf
- terraform/environment/modules/environment/ecs_api.tf
- terraform/environment/modules/environment/ecs_api_cron.tf
- terraform/environment/modules/environment/ecs_front.tf
- terraform/environment/modules/environment/ecs_pdf.tf
- terraform/environment/modules/environment/load_balancer_admin.tf
- terraform/environment/modules/environment/load_balancer_front.tf
- terraform/environment/modules/environment/vpc_data.sources.tf
- terraform/region/modules/region/subnet.tf
Remove deprecated aws_subnet_ids data source to allow Terraform version upgrades in the future
Fixes LPAL-971
Replace aws_subnet_ids data sources with aws_subnet data sources
n/a
> LPAL-971 Remove deprecated aws_subnet_ids data source

- terraform/environment/modules/environment/load_balancer_admin.tf
Require Admin users to come from an IP address listed in the https://github.com/ministryofjustice/opg-terraform-aws-moj-ip-allow-list repo.
Fixes LPAL-990
Removes the allow all rule on the Admin loadbalancer.
n/a
> LPAL-990 Tighten security group access to admin service

- .github/workflows/workflow_path_to_live.yml
Correct errors present in the path to live Github Actions workflow
Fixes LPAL-951
Correct the Channel ID used to post the Deployment message for Live and add a missing branch_name in the Docker build job.
> LPAL-951 Add branch name for Path to Live Docker build

- .github/workflows/workflow_path_to_live.yml
Run a checkout before a git command in Github Actions workflow
Fixes LPAL-951
Add checkout step to Generate image tags in path_to_live
n/a
> LPA-951 Checkout before running git command

- .github/workflows/workflow_path_to_live.yml
Correct the depth fetched by Github clone in Path to Live to get the commit sha of penultimate commit
Fixes LPAL-951
Increase the amount of commits pulled during Path to Live workflow
> LPAL-951 Correct the depth fetched in Github Clone

- .github/workflows/workflow_path_to_live.yml
Allow preprod and prod Terraform jobs to download from MOJ repos
Fixes LPAL-951
Enable `use_private_ssh_key` in the Github Actions job for `terraform_environment_production` and `terraform_environment_preproduction`
> LPAL-951 Use private key for (pre)prod environment TF

- .github/workflows/workflow_path_to_live.yml
Run Terraform apply in preprod and prod in Github Actions pipeline
Fixes LPAL-951
Change `terraform_apply` to true for preprod and prod. Uncomment the relevant `needs`  that relied on these these applies.
> LPAL-951 Apply Prod Terraform in Github Actions

- .github/workflows/workflow_path_to_live.yml
Temporarily comment out feedbackdb to allow pipeline to progress
Fixes LPAL-951
Feedback DB is temporarily commented out whilst investigating the issue with IAM permissions
> LPAL-951 Temporarily comment out feedback

- .github/workflows/cypress_tests.yml
Correct Cypress test IAM role 
Fixes LPAL-951
Assume the CI role from the management account instead of trying to assume it from an assumed role
> LPAL-951 Correct Cypress test IAM role

- .github/workflows/cypress_tests.yml
Remove the role assumption in Cypress Test workflow
Fixes LPAL-951
Remove the aws-actions/configure-aws-credentials step which assumed a role in each account.
> LPAL-951 Remove Cypress assuming role

- .github/workflows/cypress_tests.yml
- scripts/pipeline/ci_ingress/ci_ingress.py
Hardcode the dev account ID for Cypress tests when using the Caspar pseudo-mailbox and update the CI Ingress script to remove rules after running
Fixes LPAL-951
Assume several different roles during the Cypress test workflow: 
First assume a role that will allow the relevant Security Group to be changed and to access ECR,
Secondly, assume the CI role in dev so that the 'mailbox' can be accessed
Finally, assume a different role to remove the Cypress ingress rules.
> LPAL-951 Hardcode dev account for cypress tests

- .github/workflows/workflow_pr_no_changes.yml
Allow the PR workflow to be skipped if it doesn't affect any of the filtered files in the normal PR workflow
Fixes LPAL-1015
Add a second workflow that has the inverse path filter of the normal PR workflow which has a generic 'End of PR Workflow' which will always pass.
n/a
> LPAL-1015: Allow PR workflow to be skipped

- .github/workflows/workflow_destroy_on_merge.yml
- .github/workflows/workflow_path_to_live.yml
- .github/workflows/workflow_pr.yml
Prevent lock issues when running two development pipelines at once. 
Fixes LPAL-1019
Currently, the development pipeline will fail if one pipeline is already running the Terraform Apply for region, account, email or ingress due to the TF lock. This adds a 5 minute timeout to wait for the lock to be released.
> LPAL-1019 Update opg-github-workflows version

- service-front/assets/.eslintrc.json
- service-front/assets/js/moj/moj.cookie-functions.js
- service-front/assets/js/moj/moj.modules/moj.analytics.js
_Fix "useless escape" errors flagged by eslint_
_Remove not needed escape chars, remove eslint rule_
> LPAL-1000 fix not needed escape chars, remove eslint rule for application code

- LICENSE
- README.md
Add the MOJ-standard MIT license and fix the compliance badge
Fixes LPAL-1027
Use the updated endpoint for generating the badge and add in a `LICENSE file.
> LPAL-1027: Add MIT license / fix compliance badge

- .github/workflows/workflow_path_to_live.yml
- .github/workflows/workflow_pr.yml
Fix the Cypress test names so that they are easier to read in the workflow overview
Fixes LPAL-1034
The Cypress test names are now included in the job names
> LPAL-1034 Fix cypress test names

- service-front/assets/.eslintrc.json
_fixing remaining eslint issues- in this case already fixed_
_Remove rule from eslint config. Story was originally to fix the issues, but fixes to other issues have fixed this for free _
> LPAL-99 take out no-use-before-declare rule

- cypress/e2e/common/.eslintrc.json
- cypress/e2e/common/attorney.js
- cypress/e2e/common/i_am_taken_to.js
- cypress/e2e/common/i_can_find.js
- cypress/e2e/common/i_can_see_popup.js
- cypress/e2e/common/i_ignore_application_exceptions.js
- cypress/e2e/common/json.js
- cypress/e2e/common/pdfs.js
- cypress/e2e/common/reuse_details.js
_Fix no-unused-vars reported by eslint for cypress code, and take the rule out from eslint config_
_Take rule out, fix issues by hand. (not fixable automatically)_
> LPAL-1021 fix no-unused-vars for cypress code

- terraform/environment/modules/environment/rds.tf
- terraform/environment/modules/environment/variables.tf
- terraform/environment/terraform.tfvars.json
- terraform/environment/variables.tf
Clean up the Terraform codebase by removing references to the no longer used Postgres 10.
Fixes LPAL-980
Remove all references to the older Postgres in terraform/environment
> LPAL-980 Remove Postgres 10 references

- cypress/e2e/DonorPF.feature
- service-front/module/Application/view/application/authenticated/lpa/donor/form.twig
- service-front/module/Application/view/application/authenticated/lpa/primary-attorney/person-form.twig
_Currently, if you input other names longer than 50 chars, you don't get a user friendly message. This puts a user friendly message in. This is for the donor only at the moment_
_Add a helpful message in the validation of the twig files.  Add testing of this for cypress tests. Note, this is done for donor so far.  The twig for primary attorney also has an otherNames field. That doesn't currently appear to be used, but I have added a friendly message for it in case it ever is, without an associated test_
> Lpal 1031 otherNames Warning message

- cypress/e2e/common/.eslintrc.json
_Take out the no-undef rule, so that eslint does apply this.  This is a particularly important rule_
_Took out the no-undef rule from eslint config. That has meant I had to also add a number of cypress-specific globals. The end result is that the no-undef rule is now applied for everything else_
> LPAL-1020 fix cypress no-undef eslint issues

- service-front/assets/.eslintrc.json
- service-front/assets/js/govuk/stageprompt.js
- service-front/assets/js/moj/moj.modules/moj.cookie-consent.js
- service-front/assets/js/moj/moj.modules/moj.postcode-lookup.js
- service-front/assets/js/moj/moj.modules/moj.single-use.js
_fix no-unused-vars eslint warnings_
_Took out non-unused-vars rule, fixed code by hand_
> LPAL-998 fix no-unused-vars eslint warnings

- .github/workflows/workflow_destroy_on_merge.yml
- .github/workflows/workflow_path_to_live.yml
- .github/workflows/workflow_pr.yml
- terraform/environment/main.tf
Remove usage of deprecated set-output command in Github Actions
Fixes LPAL-1036
Append key:value pairs to the GITHUB_OUTPUT env var instead of using the set-output command.
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> LPAL-1036 Remove deprecated set-output command in GHA

- .github/workflows/workflow_path_to_live.yml
Add a missing step to the Github Actions Path to Live to download the Terraform artifact produced by environment run
Fixes LPAL-1036
Use the actions/download-artifact action to download the task config in preprod_terraform_outputs job.
> LPAL-1036 Add missing download artifact step

- service-pdf/src/Opg/Lpa/Pdf/AbstractLp1.php
- service-pdf/src/Opg/Lpa/Pdf/Worker/SqsWorker.php
[LPAL-1048](https://opgtransform.atlassian.net/browse/LPAL-1048)
Did a `./vendor/bin/psalm --no-cache` in all component directories. service-pdf was the only one with issues.
n/a
> LPAL-1048 Fix psalm errors in service-pdf

- node-build-assets/docker/Dockerfile
- node-build-assets/docker/start.sh
[LPAL-1047](https://opgtransform.atlassian.net/browse/LPAL-1047)
This image (only used locally) depends on the dev having run npm install inside the service-front directory. If this hasn't happened, it doesn't work correctly.
I modified this to just rely on service-front, and to do the npm install as part of the runtime script. This makes sure we populate service-front/node_modules properly and that the container always works from a cold start.
n/a
> LPAL-1047 Fix issue where node-build-assets doesn't work after git clean

- service-front/module/Application/src/Form/Lpa/AttorneyForm.php
- service-front/module/Application/tests/Form/Lpa/AttorneyFormTest.php
- service-front/module/Application/view/application/authenticated/lpa/primary-attorney/person-form.twig
_Remove unusued otherNames field from primary attorney form - legacy code cleanup and security improvement. (Note that otherNames IS used for donor,  but only the donor,  not relevant for attorneys)_
_Take otherNames out of the relevant php, twig, test_
> LPAL-1035 remove unused otherNames from primary attorney form

- terraform/environment/modules/environment/modules/aurora/main.tf
- terraform/environment/modules/environment/rds.tf
Log duration of slow DB queries and disable logging all queries.
Fixes LPAL-1039
Use Terraform to adjust the Postgres parameter groups for RDS and Aurora.
> LPAL-1039 Log duration of slow DB queries

- service-front/module/Application/src/Form/AbstractForm.php
- service-front/module/Application/tests/Form/User/ChangePasswordTest.php
- service-front/module/Application/tests/Form/User/RegistrationTest.php
[LPAL-1043](https://opgtransform.atlassian.net/browse/LPAL-1043)
See ticket.
n/a
> LPAL-1043 Allow HTML characters and trailing/leading spaces in passwords

- .github/workflows/cypress_tests.yml
Always configure Ingress Credentials to avoid the `Remove GitHub Actions runner Ingress Rule` failing if previous steps fail.
Fixes LPAL-1068
> LPAL-1068 Always configure Ingress Credentials

- .github/workflows/docker_job.yml
- docker-compose.yml
- docs/architecture/0011-implement-read-only-filesystems.md
- service-admin/docker/app/Dockerfile
- service-api/docker/app/Dockerfile
- service-front/docker/app/Dockerfile
- service-pdf/docker/app/Dockerfile
- terraform/environment/modules/environment/ecs_admin.tf
- terraform/environment/modules/environment/ecs_api.tf
- terraform/environment/modules/environment/ecs_api_cron.tf
- terraform/environment/modules/environment/ecs_feedbackdb.tf
- terraform/environment/modules/environment/ecs_front.tf
- terraform/environment/modules/environment/ecs_pdf.tf
- terraform/environment/modules/environment/locals.tf
Change the ownership of files in the container images to root and disable writing to the root file system.
Fixes LPAL-993
- Change the `chown` commands in the Dockerfiles of all of the images to use root;
- Enable readonlyRootFilesystem in ECS containers;
- Enable read_only in docker-compose;
- Create init containers which mount the /tmp volume of containers and chmod 766 to prevent the `appuser` from being able to write and execute files.
> LPAL-993 Enable read-only root filesystem on app containers

- terraform/environment/modules/environment/locals.tf
Pull busybox from official DockerHub ECR mirror to avoid DockerHub pull limits.
Fixes LPAL-1071
Changes image of initContainer.
> LPAL-1071 Pull busybox from ECR

- terraform/region/modules/region/lambda_aurora_scheduler.tf
Fix a typo in the Aurora CloudWatch events cron job
Fixes LPAL-1072
Change "commands" to "command".
> LPAL-1072 Fix typo in Aurora CloudWatch events

- terraform/region/modules/region/lambda_aurora_scheduler.tf
Change commands passed to Aurora scheduler lambda functions from list to string.
Fixes LPAL-1072
> LPAL-1072 Fix input for Aurora schedules

- service-api/module/Application/src/Model/DataAccess/Postgres/DbWrapper.php
- service-api/module/Application/src/Model/DataAccess/Postgres/UserData.php
[LPAL-1082](https://opgtransform.atlassian.net/browse/LPAL-1082)
Catch errors from laminas-db adapter when connect() fails.
n/a
> LPAL-1082 Handle connection errors gracefully without leaking stacktrace to logs

- terraform/region/modules/region/kms.tf
- terraform/region/modules/region/s3.tf
Create an S3 bucket to hold CloudWatch logs.
Fixes LPAL-1084
Create an S3 bucket with 120 day expiration policy and private ACL.
> LPAL-1084 Create bucket to hold CloudWatch logs

- terraform/region/modules/region/waf.tf
Correct the rule for allowing ON keyword
Fixes LPAL-1074
Change from json_body to just body and explicitly allow to terminate rule evaluation immediately
> LPAL-1074 Correct rule for allowing ON keyword

- .github/workflows/workflow_path_to_live.yml
Enable feedbackdb seeding in preprod and prod.
Fixes LPAL-1086
Uncomment feedbackdb seeding step in Path to Live workflow
> LPAL-1086 Uncomment feedbackdb seeding in Path to Live

- .github/workflows/docker_job.yml
- .github/workflows/workflow_path_to_live.yml
- .github/workflows/workflow_pr.yml
Promote container images through environments rather than rebuilding the same code for higher environments
Fixes LPAL-969
The container image gets created in the PR workflow and tagged with the first 7 characters of the commit SHA. When / if this gets merged into `main`, the Path to Live workflow extracts the first 7 characters of the penultimate commit (ignoring the merge commit) and checks if the image with that tag exists in ECR already. If it does, it will deploy that to preprod and prod. If not, it will recreate the image, tag it with the penultimate short commit SHA and then push to ECR.
> LPAL-969 Promote a single artifact through environments

- cypress/e2e/Errors.feature
- cypress/e2e/common/errors.js
- service-front/docker/web/etc/confd/templates/nginx.conf
[LPAL-1108](https://opgtransform.atlassian.net/browse/LPAL-1108)
See ticket.
nginx config
> LPAL-1108 Block download of potentially sensitive filename patterns

- cypress/e2e/common/encoding.js
- service-api/module/Application/src/Model/Service/ProcessingStatus/Service.php
- service-front/assets/js/moj/moj.modules/moj.postcode-lookup.js
- service-front/module/Application/src/Model/Service/AddressLookup/OrdnanceSurvey.php
- service-front/module/Application/src/Model/Service/ApiClient/Client.php
- service-front/module/Application/tests/Model/Service/ApiClient/ClientTest.php
- service-front/module/Application/view/application/authenticated/dashboard/index.twig
[LPAL-1111](https://opgtransform.atlassian.net/browse/LPAL-1111)
See ticket.
n/a
> LPAL-1111 Make use of Accept* headers and charsets more consistent

- .github/workflows/workflow_destroy_on_merge.yml
- scripts/pipeline/workspace_cleanup/destroy_workspace.sh
- scripts/pipeline/workspace_cleanup/workspace_cleanup.sh
Destroy temporary workspaces on merge to main
Fixes LPAL-1115
Write a second script to destroy a single workspace and update the workspace_cleanup script to have accurate help text.
> LPAL-1115 Fix destroy workspace on merge to main

- .github/workflows/workflow_destroy_on_merge.yml
- scripts/pipeline/workspace_cleanup/destroy_workspace.sh
Do not assume the dev role when destroying workspaces
Fixes LPAL-1115
Removes the assume-role before running the destroy ephemeral workspace script
> LPAL-1115 Do not assume dev role

- terraform/environment/modules/environment/ecs_api.tf
- terraform/environment/modules/environment/ecs_feedbackdb.tf
- terraform/environment/modules/environment/ecs_seeding.tf
- terraform/environment/modules/environment/locals.tf
Cleanup unnecessary DB local variables in Terraform code
Fixes LPAL-1118
Uses the module output values directly rather than having unnecessary ternaries to set local vars
> LPAL-1118 Cleanup DB locals

- .github/actions/detect_changes/action.yml
- .github/workflows/docker_job.yml
- .github/workflows/workflow_destroy_on_merge.yml
- .github/workflows/workflow_path_to_live.yml
- .github/workflows/workflow_pr.yml
Reduce the amount of time the pipeline takes to complete by only building Docker images if their code has changed
Fixes LPAL-1119
Change the workflow so that it only rebuilds images when their directory or the shared directory has been changed.
The pipeline will fail until manual steps are taken. Before merging to main, all currently live images will need additional tags adding to be prefixed with main-
https://github.com/ministryofjustice/opg-modernising-lpa/pull/230
> LPAL-1119 Build docker images only if changed

- scripts/pipeline/workspace_cleanup/destroy_workspace.sh
- scripts/pipeline/workspace_cleanup/workspace_cleanup.sh
Fix workspace cleanup to exit cleanly if there are no workspaces to cleanup
Fixes LPAL-1120
Change script so that there are no unbound variables
> LPAL-1120 Fix workspace cleanup to exit cleanly

- service-api/docker/web/etc/confd/templates/nginx.conf
- service-api/docker/web/etc/confd/templates/nginx.conf.dev
- service-front/docker/web/etc/confd/templates/nginx.conf
- shared/docker/web/etc/confd/templates/nginx.conf.service-admin
Fix the path for ./well-known/security.txt so that security researchers are able to contact the MOJ Digital & Technology Security & Privacy team
Fixes LPAL-1098
Rename well_known to well-known in nginx configs
https://www.rfc-editor.org/rfc/rfc5785
> LPAL-1098 Correct path of well-known in nginx

- terraform/environment/modules/environment/ecs_cluster.tf
- terraform/environment/modules/environment/ecs_front.tf
- terraform/environment/modules/environment/secrets.tf
- terraform/region/secrets.tf
Cleanup of Terraform code
Fixes LPAL-1123
Remove no longer needed SendGrid secrets and environment variables
> LPAL-1123 Remove SendGrid references

- service-front/module/Application/src/Model/Service/ApiClient/Response/AuthResponse.php
- service-front/module/Application/src/Model/Service/Authentication/Adapter/LpaAuthAdapter.php
- service-front/module/Application/src/Model/Service/Authentication/Identity/User.php
- service-front/module/Application/tests/Model/Service/Authentication/Adapter/LpaAuthAdapterTest.php
- service-front/module/Application/tests/Model/Service/Authentication/Identity/UserTest.php
Unit tests were failing because of a condition which sets the last login for the user to 'now' if the supplied last login datetime is more than 5 years ago. This was tripped when we passed 2023-01-04, as some of the tests set the last login date to 2018-01-02.
Remove this condition and instead set a default lastLogin if one is not available for a user during an authentication attempt. Also allow the lastLogin to be null when constructing a User, and default to 'now' if this is the case. As we only construct users in LpaAuthAdapter, we shouldn't hit this case, but it is covered anyway.
In LpaAuthAdapter, default the last login to null if the user doesn't have one. Then, when constructing the last login datetime, a null value will mean we default to 'now'.
Fixes LPAL-1126
_Explain how your …
> LPAL-1126 Remove check which fails if lastLogin > 5 years ago

- .github/workflows/cypress_tests.yml
- .github/workflows/docker_job.yml
Reduce the amount of time taken for Cypress tests to run
Fixes LPAL-970
Run Cypress tests directly on Github Actions runner, removing the need to build the Cypress docker container in CI and remove the need to docker pull it.
[LPAL-970]: https://opgtransform.atlassian.net/browse/LPAL-970?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LPAL-970 Run Cypress tests on Github Actions runner

- .github/workflows/_smoke_tests.yml
- .github/workflows/workflow_path_to_live.yml
Announce Path to Live failures in Slack
Fixes LPAL-1094
Changes the logic so that failure messages display if there is a job failure and the success only sends if smoke tests pass
> LPAL-1094: Announce Path to Live failures in Slack

- .github/workflows/workflow_path_to_live.yml
Update the Slack message to mark a Path to Live run as complete only if the smoke tests pass. Otherwise, mark it as failed.
Fixes LPAL-1145
> LPAL-1145 Mark workflow as complete when tests OK

- terraform/environment/modules/environment/cloudwatch_alarms.tf
- terraform/environment/modules/environment/cloudwatch_logs.tf
Create two metrics and associated alarms for application 5XX / 401 / 403 errors. These will allow Slack alerts to be generated if we begin generating these in the applications. Currently, we only alert if the ELB generates these.
Fixes LPAL-1147
Create two metric filters: one for application 5xx errors and one for 401/403 errors. Due to how we log, these are aggregate stats of all of Make's applications. There is scope to change the way that we log in the future so that these can be broken down by application.
An alarm for each metric is then created.
> LPAL-1147 Create metric for application errors

- service-front/module/Application/src/Controller/General/RegisterController.php
- service-front/module/Application/tests/Controller/General/RegisterControllerTest.php
[LPAL-1151](https://opgtransform.atlassian.net/browse/LPAL-1151)
See ticket.
n/a
[LPAL-1151]: https://opgtransform.atlassian.net/browse/LPAL-1151?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LPAL-1151 Fix 500 errors caused by invalid scheme in Referer header

- .github/workflows/docker_job.yml
- docs/runbooks/terraform_state_locks.md
[LPAL-1158](https://opgtransform.atlassian.net/browse/LPAL-1158)
Use `aws ecr describe-images | jq` to find the latest main-* image.
AWS ECR CLI
[LPAL-1158]: https://opgtransform.atlassian.net/browse/LPAL-1158?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Find latest main image via aws rather than guessing from git commit ID

- .github/workflows/analysis-tfsec.yml
This uses a later tfsec-sarif-action version (0.1.4) which no longer uses wget to fetch the tfsec versions, and instead installs tfsec directly into the docker image. Hopefully this will fix our 403 rate limit exceeded errors.
[LPAL-1159](https://opgtransform.atlassian.net/browse/LPAL-1159)
-
tf
[LPAL-1159]: https://opgtransform.atlassian.net/browse/LPAL-1159?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LPAL-1159 Upgrade to latest "moj tfsec to github security" action

- renovate.json
[LPAL-1162](https://opgtransform.atlassian.net/browse/LPAL-1162)
See ticket.
Renovate.
[LPAL-1162]: https://opgtransform.atlassian.net/browse/LPAL-1162?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LPAL-1162 Tweak Renovate config for exclusions and range strategy

- service-api/module/Application/src/Controller/PingController.php
- service-api/module/Application/src/ControllerFactory/PingControllerFactory.php
- service-api/module/Application/tests/Controller/PingControllerTest.php
- service-api/module/Application/tests/ControllerFactory/PingControllerFactoryTest.php
Inject AWS credential provider into service-api ping controller so that unit tests can run locally without need for `aws-vault`
Fixes [LPAL-1075](https://opgtransform.atlassian.net/browse/LPAL-1075)
[LPAL-1075]: https://opgtransform.atlassian.net/browse/LPAL-1075?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LPAL-1075 Fix service-api unit tests so it doesn't need aws-vault in front of it

- renovate.json
[LPAL-1174](https://opgtransform.atlassian.net/browse/LPAL-1174)
* Update cypress Dockerfile and package*.json files at the same time.
* Don't do any major updates.
* Prevent updates to php, python, redis and postgres.
* Don't update PHP PDF libraries.
Renovate is not my friend.
[LPAL-1174]: https://opgtransform.atlassian.net/browse/LPAL-1174?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LPAL-1174 Restructure renovate config

- renovate.json
Missed this when reworking the config. Causes a validation error.
[LPAL-1174](https://opgtransform.atlassian.net/browse/LPAL-1174)
n/a
n/a
[LPAL-1174]: https://opgtransform.atlassian.net/browse/LPAL-1174?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LPAL-1174 Fix incorrect property in renovate config

- service-front/assets/js/moj/moj.js
[Incident](https://incident.opg.service.justice.gov.uk/incident/694/) created as we were capturing some personal data in Google Analytics.
This fix should disable the capturing of form validation errors altogether to prevent any event data being sent to GA.
> Disabling capturing of form validation errors

- renovate.json
_LPAL-1180 although we removed service-front-v2 and opg-feedback is built seperately then pulled in, we still have python scripts for the infrastructure side, so enable the python managers in renovate to keep these up to date_
_Modify renovate config_
> LPAL-1180 enable python in renovate config

- service-api/module/Application/src/Controller/PingController.php
- service-api/module/Application/tests/Controller/PingControllerTest.php
- service-front/module/Application/src/Model/Service/System/Status.php
- service-front/module/Application/tests/Model/Service/System/StatusTest.php
- shared/module/MakeShared/src/Logging/LoggerTrait.php
[LPAL-1160](https://opgtransform.atlassian.net/browse/LPAL-1160)
**Note: this branch is based off the LPAL-473 branch, and should be merged after that one.**
See ticket.
n/a
[LPAL-1160]: https://opgtransform.atlassian.net/browse/LPAL-1160?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LPAL-1160 Remove 6-times loop from ping status page

- Makefile
- renovate.json
- service-admin/composer.json
- service-admin/composer.lock
- service-admin/docker/app/Dockerfile
- service-api/composer.json
- service-api/composer.lock
- service-api/docker/app/Dockerfile
- service-front/composer.json
- service-front/composer.lock
- service-front/docker/app/Dockerfile
- service-front/package-lock.json
- service-pdf/composer.json
- service-pdf/composer.lock
- service-pdf/docker/app/Dockerfile
- shared/composer.json
- shared/composer.lock
[LPAL-1188](https://opgtransform.atlassian.net/browse/LPAL-1188)
[LPAL-1189](https://opgtransform.atlassian.net/browse/LPAL-1189)
The aim is to get everything in the codebase up to date as far as possible, alongside a working Renovate config.
* Fix Python renovate config by moving to separate package rule and fixing typos in manager names.
* Define a specific version of PHP for all components, so Renovate doesn't try to use the wrong version. Set this in Dockerfile and composer.json.
* Update all deps manually for npm and composer.
* Split PHP 8.1 and 8.2 updates into different rulesets. This forces Renovate to use the right PHP version, based on the setting in composer.json under config.platform.php.
* Update to composer 2.5.5 throughout.
* Modify how composer containers are used in the …
> LPAL-1188/LPAL-1189 Renovate config, dep updates, composer upgrade, PHP pin, Python renovate fix

- renovate.json
> LPAL-1189 Missed these python manager references in renovate.json

- docker-compose.yml
Use a version of Redis in docker-compose that matches the major version used in AWS.
Fixes LPAL-1203
Change the version of redis in docker-compose.yml to a fixed version.
> LPAL-1203 Change version of local redis

- cypress/e2e/DonorHW.feature
- cypress/e2e/DonorPF.feature
Fix broken cypress tests where 5 addresses were expected but only 2 were returned.
Fixes LPAL-1215
> LPAL-1215 Correct cypress asserts on num of option

- terraform/account/cloudwatch.tf
- terraform/region/modules/region/cloudwatch.tf
Move Cloudwatch Log Group from Account Terraform state to Region Terraform state
Fixes LPAL-573
> LPAL-573 Move Cloudwatch Log Group to region

- .github/workflows/workflow_path_to_live.yml
_Add continue on error to locust tests, as a failure in the load test is not a reason to fail the build when all other tests have passed_
_add continue on error flag to locust test section_
> prevent failure in locust test from failing whole build

- .github/workflows/analysis-psalm.yml
- .github/workflows/phpunit.yml
- service-front/composer.json
- service-front/composer.lock
- service-front/docker/app/Dockerfile
- service-front/module/Application/src/Model/Service/Signatures/DateCheck.php
- service-front/module/Application/tests/View/DateCheckViewModelHelperTest.php
Update PHP and application dependencies from 8.1 to 8.2 in service-front.
Fixes LPAL-1078
The base alpine image is 3.16 instead of anything later due to issues found with later versions in LPAL-1139.
https://github.com/openssl/openssl/issues/17064
> LPAL-1078 Update service-front to PHP 8.2

- terraform/environment/modules/environment/ecs_cluster.tf
- terraform/environment/modules/environment/ecs_pdf.tf
Use Fargate Spot for service-pdf to reduce cost of PDF container.
Fixes LPAL-1225
Update the Terraform code to use FARGATE_SPOT capacity provider for service-pdf.
> LPAL-1225 Using Fargate Spot for service-pdf

- service-pdf/composer.lock
Rebuild dependabot update.
Bumps [guzzlehttp/psr7](https://github.com/guzzle/psr7) from 2.4.4 to 2.5.0.
- [Release notes](https://github.com/guzzle/psr7/releases)
- [Changelog](https://github.com/guzzle/psr7/blob/2.5/CHANGELOG.md)
- [Commits](https://github.com/guzzle/psr7/compare/2.4.4...2.5.0)
---
updated-dependencies:
- dependency-name: guzzlehttp/psr7 dependency-type: indirect ...
> Bump guzzlehttp/psr7 from 2.4.4 to 2.5.0 in /service-pdf

- service-api/docker/pgbouncer/Dockerfile
- terraform/environment/modules/environment/ecs_api.tf
Explicitly set the `PGBOUNCER_AUTH_TYPE` as a breaking change was introduced to the 1.19.1 rolling tag which caused increased CPU usage in the pgbouncer containers.
Fixes LPAL-1232
Explicitly set `PGBOUNCER_AUTH_TYPE` to its old default value of `md5` and pin the version used to `1.19.1-debian-11-r16`.
https://www.postgresql.org/docs/current/auth-password.html
https://docs.bitnami.com/kubernetes/infrastructure/postgresql/configuration/understand-rolling-immutable-tags/
https://github.com/bitnami/containers/commit/190481f04144fe8ff1247da6fc7ed605951352b4
> LPAL-1232 Pin pgbouncer to immutable tag

- renovate.json
Enable pip-compile updates in renovate.
Fixes LPAL-1234
Allow requirements.in to be updated.
https://docs.renovatebot.com/modules/manager/pip-compile/
> LPAL-1234 Enable pip-compile updates

- .github/workflows/workflow_path_to_live.yml
- .github/workflows/workflow_weekly_refresh.yml
Update the Slack channel used to announce prod deployments
Fixes LPAL-1235
> LPAL-1235 Use different Slack deploy channel

- service-admin/docker/app/Dockerfile
- service-api/docker/app/Dockerfile
- service-front/docker/app/Dockerfile
Upgrade API, Front and Admin container base images to Alpine 3.18.
Fixes LPAL-1236
Change Dockerfile to use `php:8.2-fpm-alpine3.18`. Testing in the dev environment shows that previous performance regressions that existed with OpenSSL 3.0 so not exist in OpenSSL 3.1.
https://www.openssl.org/blog/blog/2023/03/07/OpenSSL3.1Release/
> LPAL-1236 Upgrade to alpine3.18

- renovate.json
_Seperate renovate config out for the individual services. This alllows us to let through upgrades where the build is passing, and individually target and investigate changes which broke the build in 1 service only_
_Update renovate config with these changes_
> Lpal 1249 splitrenovate

- cypress/e2e/Cookies.feature
- docker-compose.yml
_Build keeps failing because cypress checks for cookies to be set before they are ready_
_Comment out cookie test scenarios. Also fix keys in local docker-compose which aren't allowed to have hyphen in secrets anymore_
> Fix build by for now commenting flaky cookie tests

- renovate.json
_Due to some open PRs that cannot be merged swiftly, renovate has not been creating new ones. It is possible to trigger new renovate PRs by hand to get updates through, however its not obvious which are mature enough, so better to let renovate decide when to create a PR. Allowing more concurrency allows this_
_Edit renovate.json_
> allow concurrent PRs by renovate

- terraform/environment/modules/environment/modules/aurora/main.tf
- terraform/environment/modules/environment/modules/aurora/variables.tf
Update CA certificate for RDS instance
Fixes LPAL-1254
Update the certificate used by RDS for TLS. No updates to the client necessary.
> LPAL-1254 Update CA certificate for RDS

- terraform/environment/main.tf
- terraform/environment/modules/dns/main.tf
- terraform/environment/modules/dns/terraform.tf
- terraform/environment/modules/environment/load_balancer_front.tf
Add DNS health check for Make an LPA public front end.
Fixes LPAL-1255
Create health check resource and change loadbalancer to allow HTTPS connections from AWS health check IP addresses.
> LPAL-1255 Add DNS health check for Make

- .github/workflows/workflow_destroy_on_merge.yml
- .github/workflows/workflow_terraform_environment_cleanup.yml
Fix Terraform Workspace cleanup and Terraform destroy on merge to main.
Fixes LPAL-1256
Install the required version of Terraform before attempting to run Terraform.
> LPAL-1256 Fix Terraform destroy for dev envs

- docker-compose.yml
- local-config/start.sh
- service-admin/docker/app/Dockerfile
- service-api/config/autoload/global.php
- service-api/docker/app/Dockerfile
- service-pdf/bin/start.sh
- service-pdf/config/global.php
- service-pdf/docker/app/Dockerfile
_PDF tests were broken locally because service-pdf and service-api could not talk to sqs. Fix this, and fix debugging for local services with xdebug/phpstorm_
- service-front was already working with debugger. Rejig other services dockerfiles to be like service-front's 
- Upgrade localstack in docker-compose. Add endpoint parameter to config for service-pdf and service-api, which appears to now be needed by AWS SDK.
- Change style of address for sqs queue to be more as expected by AWS (Greg's suggestion)
-  service_pdf needed a couple of XDEBUG related vars setting in docker-compose , to switch on debugger as that is a script not a full app (full app the debugger switches on anyway without such a nudge)
- changed service-pdf-bin/start.sh to not require bash to run - no need for this and …
> LPAL-1276 fix locally running of cypress pdf tests and fix xdebug for admin, pdf, api

- .github/workflows/analysis-trivy.yml
- .github/workflows/workflow_pr.yml
Remove duplicated dfsec/tfsec checks from Trivy.
Fixes LPAL-1279
> LPAL-1279 Remove TF code duplicate checks

- terraform/environment/modules/dns/main.tf
Re-add the non-www DNS record for production. This will be redirected to www. by the front ALB.
Fixes LPAL-1282
Add a new `aws_route53_record` to the DNS module which is only created in production.
> LPAL-1282 Re-add non-www DNS record

- terraform/environment/modules/dns/main.tf
Add SPF / DMARC records for public-facing domain names.
Fixes LPAL-1284
Create and populate SPF / DMARC records using `aws_route53_record` resources
> LPAL-1284 Add SPF / DMARC records for public facing domains

- terraform/environment/modules/dns/main.tf
Correct DNS zones used to create SPF / DMARC records.
Fixes LPAL-1284
> LPAL-1284 Correct DNS zones used to create SPF / DMARC records

- terraform/environment/modules/environment/cloudwatch_alarms.tf
We currently trigger an alarm when we have =>6 messages in the queue for 1 minute. This is unnecessary as the `service-pdf` can easily scale to handle this so this alarm is currently a proxy for "service-pdf is scaling by +1". This PR will change the alarm to only trigger if the `ApproximateNumberOfMessagesVisible` is >=10 for 5 minutes to reduce the amount of alarms we get in Slack as this would suggest that messages are not being consumed from the queue.
Fixes LPAL-1290
Change alarms in Terraform.
> LPAL-1290 Delay triggering PDF alarms

- terraform/region/modules/region/cloudwatch.tf
Remove ECS state change alarm for development to avoid creating unnecessary alarms in ephemeral envs.
Fixes LPAL-1290
> LPAL-1290 Remove ECS state change alarm for development

- .github/workflows/workflow_path_to_live.yml
Fix intermittent issues with Cypress tests failing
Fixes LPAL-1291
Ensure that the database seeding task is completed before running the Cypress tests in Path to Live.
> LPAL-1291 Wait for seeding to complete before running Cypress tests

- .github/workflows/workflow_pr.yml
Remove Jira actions from Github Workflows 
Fixes LPAL-1294
> LPAL-1294 Remove Jira actions

- service-admin/docker/app/Dockerfile
- service-api/docker/app/Dockerfile
- service-front/docker/app/Dockerfile
Bumps php image from php:8.2-fpm-alpine3.18 to php:8.2-fpm-alpine3.20
Fixes LPAL-1304
> bump image ver to 3.20

- .github/workflows/workflow_pr.yml
Prevent the PR from being merged when the end_of_workflow job has been skipped.
Fixes LPAL-1321
> LPAL-1321: only pass end_of_workflow when pipeline actually succeeds

- .github/workflows/workflow_destroy_on_merge.yml
Updates the `destroy_on_merge` to use the latest `branch-name` action to find workspaces to destroy
Fixes LPAL-1323
> LPAL-1323: update destroy to branch-name

- .github/workflows/workflow_path_to_live.yml
- .github/workflows/workflow_pr.yml
Adds the account and region Terraform to be required to continue the pipeline into the seeding tasks
Fixes LPAL-1342
> LPAL-1342: pipeline stop on failure

- renovate.json
Adds an ignore dependency block to Renovate config to ignore an error.
> Update renovate config with ignore deps

- .github/workflows/workflow_path_to_live.yml
- .github/workflows/workflow_pr.yml
Shrink the height of slack success and failed notifications in an effort to reduce channel spam fatigue
* I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant
* I have added tests to prove my work
* I have added mandatory tags to terraformed resources, where possible
* If I have a new OPG component dependency, I have updated the `metadata.json` with the repo location.
* If I added a package.json or composer.json, I also made sure this is included in the script in `.github/workflows/dependabot-update.yml`
* The product team have tested these changes
> Shrink the slack notifications on build

- package-lock.json
Updates cross-spawn to fix CVE-2024-21538
Fixes UML-3873
Ran `npm update cross-spawn` to target the npm package causing the CVE.
> UML-3873: upate cross-spawn

- service-api/composer.json
- service-api/composer.lock
- service-api/module/Application/tests/Library/Authentication/Adapter/LpaAuthTest.php
- service-api/module/Application/tests/Library/Authentication/AuthenticationListenerTest.php
- service-api/module/Application/tests/Model/DataAccess/Postgres/UserDataTest.php
- service-api/module/Application/tests/Model/Service/ProcessingStatus/ServiceTest.php
- service-api/module/Application/tests/Model/Service/ServiceAbstractFactoryTest.php
- service-api/phpunit.xml
- service-api/tests/integration/UserDataTest.php
Update to PHPUnit 10 for better compatibility with later versions of PHP, and to have access to features like moving from Annotations to Attributes for Test configuration
- Update PHPUnit and Mockery packages
- Update PHPUnit config
- Rename AbstractAuthControllerTest to AbstractAuthControllerTestCase
- Rename AbstractControllerTest to AbstractControllerTestCase
- Rename AbstractServiceTest to AbstractServiceTestCase
- Make dataProviders static
- Declare dynamically declared properties in Tests
> Migrate API to PHPUnit 10

- cypress/e2e/AdminUserAccount.feature
- cypress/e2e/DashboardDeleteLpa.feature
- cypress/e2e/PasswordReset.feature
- cypress/e2e/ReusedDonorKeepsAllDetails.feature
- cypress/e2e/SignOut.feature
- cypress/e2e/SignUpWithFixtures.feature
- cypress/e2e/SignupAndChangeDetails.feature
- service-front/module/Application/src/Form/User/SetPassword.php
- service-front/module/Application/tests/Form/User/ChangePasswordTest.php
- service-front/module/Application/tests/Form/User/RegistrationTest.php
- service-front/module/Application/tests/Form/User/SetPasswordTest.php
- service-front/module/Application/view/application/authenticated/change-password/partials/index-error-summary.twig
- service-front/module/Application/view/application/general/forgot-password/partials/reset-password-error-summary.twig
- service-front/module/Application/view/application/general/register/partials/index-error-summary.twig
- service-front/module/Application/view/application/partials/password-rules.twig
- service-pdf/src/Opg/Lpa/Pdf/AbstractIndividualPdf.php
_Increase password length to 12 chars_
_Change validators and tests to be 12 chars instead of 8_
> LPAL-1037 longer password

- .idea/php.xml
- service-api/composer.json
- service-api/composer.lock
- service-api/module/Application/tests/Model/Service/Pdfs/ServiceTest.php
It was used in a test to encrypt a string, but that's not necessary since the code under test doesn't do any decryption (it happens inside the library being mocked out).
This also removes laminas-math.
Fixes LPA-3838 #patch
I updated the test to assert the response first, confirming no decryption was happening, then simplified the mocked data to not used laminas-crypt.
* N/A
* N/A
* N/A
* N/A
* N/A
> Remove laminas-crypt from service-api

- renovate.json
It makes no sense to hard code PHP versions into the strings for rennovate PR names/branch names. It's enought to say they're PHP updates.
Hardcoding just means they fall out of date (as they are now)
* I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant
* I have added tests to prove my work
* I have added mandatory tags to terraformed resources, where possible
* If I have a new OPG component dependency, I have updated the `metadata.json` with the repo location.
* If I added a package.json or composer.json, I also made sure this is included in the script in `.github/workflows/dependabot-update.yml`
* The product team have tested these changes
> Remove hardcoded PHP versions strings from rennovate
