terraform/terraform_environment/load_balancer_load.tf
This is only a requirement for front, thus not added to admin.
=> Added HTTP -> HTTPS redirect

README.md
I just need to change something/anything in order to trigger the master pipeline.
=> Test extended healthcheck

terraform/terraform_environment/load_balancer_front.tf
`https://lastingpowerofattorney.service.gov.uk/home` -> `https://www.lastingpowerofattorney.service.gov.uk/home`
=> Redirect domain apex to www

docker-compose.yml
Fixes missing parts of the docker-compose
=> Added missing volume mount & set correct path

service-front/module/Application/view/application/general/home/index.twig
https://opgtransform.atlassian.net/browse/LPA-3618
Fixes LPA-3618
Added a content with URL linking to survey monkey. This content is for a temporary period and will be removed on request later.
_Any tips and tricks, blog posts or tools which helped you. Plus anything notable you've discovered about the Refunds service_
=> Added a survey monkey url to home page

service-front/module/Application/view/application/general/auth/index.twig, service-front/module/Application/view/application/general/home/index.twig
https://opgtransform.atlassian.net/browse/LPA-3632
Fixes LPA-3632 and LPA-3631
Added a link to the pages which is temporary until asked to be removed.
Just a content addition.
=> Lpa 3632 add new survey link on home and login page

service-front/module/Application/view/application/authenticated/lpa/status/index.twig, service-front/module/Application/view/application/general/home/contact.twig, service-front/module/Application/view/email/layout/layout.twig
https://opgtransform.atlassian.net/browse/LPA-3647
Fixes LPA-3647
Changed content in twig template
_Any tips and tricks, blog posts or tools which helped you. Plus anything notable you've discovered about the Refunds service_
=> content change to work timings

service-front/module/Application/view/application/authenticated/lpa/status/index.twig
To update content around lead times, as per the business's request
Fixes LPA-3709
content change in a twig file.
N/A
=> LPA-3709 Update content about longer lead times.

service-front/module/Application/view/application/general/auth/index.twig, service-front/module/Application/view/application/general/home/index.twig
To remove survey monkey links
Fixes LPA-####
remove links and blurb from twigs.
N/A
=> LPA-3729 remove survey from twigs

terraform/account/credentials.tf, terraform/account_ingress/credentials.tf, terraform/email/credentials.tf, terraform/environment/credentials.tf, terraform/terraform_maintenance/credentials.tf
_Version 3 of AWS provider has breaking changes with ACM_
_Pins the version of the provider to 2.70_
=> Set the provider version directly

terraform/environment/ecs_admin.tf, terraform/environment/ecs_api.tf, terraform/environment/ecs_api_cron.tf, terraform/environment/ecs_front.tf, terraform/environment/ecs_pdf.tf
Check that the product runs ok on Fargate platform version 1.4.0
Fixes LPA-3725
=> Check that the product runs ok on Fargate platform version 1.4.0

terraform/environment/rds.tf
Attach custom param group again for pre-prod
=> LPA-3447 join the param group back on

service-front/package-lock.json, service-front/package.json
Fixes LPAL-40, amongst others
run npm audit fix
_Any tips and tricks, blog posts or tools which helped you. Plus anything notable you've discovered about the Refunds service_
=> fix npm audit - remove vulnerabilities

service-front/content/guidance/Process_Signing the LPA.md, service-front/module/Application/view/application/authenticated/lpa/complete/complete.twig, service-front/module/Application/view/application/authenticated/lpa/complete/view-docs.twig, service-front/module/Application/view/layout/twig/layout.twig
_JIRA tickets LPAL-43, 44, 36, 47_
_Change around h2s and h3s both in twigs and in markdown that results in html, add title text for lpa-47, re-run axe browser plugin to verify issues no longer reported_
=> Accessibility fixes for multiple stories

service-front/module/Application/view/application/authenticated/lpa/date-check/index.twig
AXE audit shows all labels on date checker page were not correctly set for the corresponding input fields. 
Fixes LPAL-46
=> Lpal 46 signed date checkerlabel

docs/runbooks/cloud9/db_access.md
changes to the runbook for Cloud9 based on developer feedback.
Following a supervised "hot run" of cloud9 DB runbook, we noticed minor issues with the wording. 
This clarifies the wording and highlights in the MD file, based on the issues raised.
=> clarifications to cloud9 runbook based on use with devs

terraform/account/workspace_cleanup.tf
when workspace cleanup was implemented, we didn't switch on TTL field correctly. this fix addresses that, meaning that the workspaces can now clean up more regularly.
fix ttl field, and adjust lifecycle to keep table in place.
- recheck your resources!
=> Fix ttl on workspace cleanup (ACCOUNT LEVEL CHANGE)

scripts/pipeline/check_ecr_scan_results/aws_ecr_scan_results.py
see https://github.com/ministryofjustice/opg-use-an-lpa/pull/595/files
- fix issue with scan results. this is is a quick fix.
condition placed around description to check for value.
=> Fix ECR scan results (as per UML-1118)

docker-compose.yml
_ pin composer version in docker-compose_
=> bugfix - pin composer version in docker-compose 

docs/runbooks/cloud9/db_access.md, docs/runbooks/generating_stats/run_report.md, docs/runbooks/redeploying_environments/redeploying_environments.md, docs/runbooks/replacing_secrets.md, docs/runbooks/seeding_non_live_environments/seeding_non-live_environments.md, docs/runbooks/setting-up-aws-credentials/setting-up-credentials.md, docs/runbooks/setting_admin_users/README.md, docs/runbooks/troubleshooting_container_images/troubleshooting_container_images.md
- To update runbooks to have further troubleshooting instructions, especially around docker containers.
- To reuse some requirements instructions (DRY)
=> Update runbooks for docker container debug and restructure

.circleci/config.yml, terraform/environment/resource_group.tf, terraform/environment/versions.tf
to upgrade the environment portion of terraform. this is step 1 of several steps to upgrade tf and aws providers associated with it. 
Fixes LPAL-186
- support both 0.12 and 0.13 in circleci (environment to be updated)
- migrate environment tf to correct version
=> LPAL-186 upgrade environment terraform

docker-compose.yml, service-admin/docker/app/Dockerfile, service-api/docker/app/Dockerfile, service-front/docker/app/Dockerfile, service-pdf/docker/app/Dockerfile, tests/Dockerfile
_Try out composer 2 against Laminas upgrade_
=> try out composer 2 latest

terraform/account/certificate.tf, terraform/account/s3.tf, terraform/account/versions.tf, terraform/account_ingress/versions.tf, terraform/email/versions.tf
perform a terraform aws provider upgrade on account, ingress and email, follows on from previous PR #180 
Fixes LPAL-190
- audit account, account ingress and email terraform for potential changes.
- upgrade terraform provider to `~> v3.0`
- use the guide to change relevant resources.
- requires state moves and removals due to  changes in format of aws_acm_certificate and associated route 53 records. 
- The following state moves and removals will also take place. this is based on the advice given in the [Version 3 upgrade](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-3-upgrade#resource-aws_acm_certificate) :
``` bash
tf state mv 'aws_route53_record.certificate_validation_front' 'aws_route53_record.certificate_validation_front["*.front.lpa.opg.service.just …
```
=> Lpal 190 aws provider upgrade account

docs/runbooks/troubleshooting_container_images/troubleshooting_container_images.md
Fix inconsistencies in the container troubleshoot runbook
Fix container names /tag references
=> corrections to runbook for container diagnostics

docker-compose.yml, scripts/non_live_seeding/seed_environment.sh, service-api/docker/app/db-migrations.sh, service-seeding/docker/app/Dockerfile, tests/functional/tests/05-CreatePfLpa/05-primary-attorney.js, tests/functional/tests/05-CreatePfLpa/07-replacement-attorney.js
Work to get functional tests running locally.
Fixes LPAL-206.
* Improve start up sequence of docker containers esp. so that SQL going to postgres from different places doesn't cross beams:
* api app waits before applying migrations
* seeding waits for tables created by api app migrations before inserting seed data
* Improve tests and scripts so they don't have unnecessary waits:
* casperjs tests use waitForSelector() rather than wait() for set time period
* Waits in seeding script replaced with polling for endpoints/db
* Reduce weight of docker container for seeding (doesn't require Python only Alpine)
Functional tests are fragile and inconsistent, and PDF generation hangs for a very long time (on my local setup, I'm still unable to generate LP3 PDF in under 8 minutes).
=> LPAL-206 Further functional test and local run improvements

terraform/account/certificate.tf, terraform/account/locals.tf, terraform/environment/dns.tf, terraform/environment/locals.tf, terraform/environment/vpc_data.sources.tf
post clean up actions after premature DNS switch over
Fixes LPAL-193
- correctly align cert details for live environment
- align DNS record for www prefix in prod.
- clarify some of the calculated locals
- remove old legacy dns settings where possible
=> LPAL-193 fix production after prod DNS change

terraform/environment/dns.tf, terraform/environment/rds.tf
dns record to have allow overwrite on terraform. for update in place.
Fixes LPAL-193
- `allow_overwrite = true`
-  some formatting happened also
=> allow overwrite of A record

scripts/non_live_seeding/seed_environment.sh, scripts/pipeline/start_seeding_task/ecs_start_seeding_task.py
The seeding script can fail but the build succeed. This may put the app into an incorrect state.
Ensure that we return an indicative exit code to the ECS task so that we can fail the build if the seeding script fails.
Fixes LPAL-209
* Fix the seeding shell script to return an exit code if db is not available (it already returns an exit code for other bad conditions).
* Check the exit code from the task in the Python script which runs the seeding shell script, and use this as the return code for the Python script.
Difficult to test the ECS task runner, as it relies on a ton of environmental setup. Consequently, the only way I could think of to easily test was to push a commit which deliberately returned a bad exit code. This suggests we need a better way to test these scripts in isolation. …
=> LPAL-209 ECS seeding task improvements

service-admin/composer.lock, service-api/composer.lock, service-front/composer.lock, service-pdf/composer.lock, tests/composer.lock
To update composer lock files to keep up to date.
- tests
- service-front
- service-api
- service-admin
- service-pdf
`composer update --prefer-dist --no-suggest --no-interaction --no-scripts --optimize-autoloader --ignore-platform-reqs`
N/A
=> composer updates

terraform/environment/ecs_admin.tf, terraform/environment/terraform.tfvars.json
Optimize ECS container sizes where needed.
Fixes LPAL-304
reduce task count and size to admin container for production. this service is rarely used, and is oversized.
MOJ INTERNAL: SEE: https://docs.google.com/spreadsheets/d/1Jv74j0y4iXiEGz1aC_SCDoL4aNkBOjYNeyHsiU1TQvI/edit#gid=0
=> LPAL-304 tweaks to admin (sizes and desired tasks)

service-admin/composer.lock, service-api/composer.lock, service-front/composer.lock, service-pdf/composer.lock, tests/composer.lock
weekly composer.lock update
- service-front
- service-api 
- service-admin
- service-pdf
- tests
Fixes LPAL-312
run `composer update --prefer-dist --no-suggest --no-interaction --no-scripts --optimize-autoloader --ignore-platform-reqs`
=> LPAL-312 update composer lock versions

scripts/run_outdated_scripts/update_outdated.sh, service-admin/composer.lock, service-api/composer.lock, service-front/composer.lock, service-front/package-lock.json, service-pdf/composer.lock, tests/composer.lock
weekly package update
- includes a script to run across the repo.
- `composer update`
- `npm update`
- Add script
=> dependabot weekly update 

service-admin/composer.lock, service-api/composer.lock, service-front/composer.lock, service-front/package-lock.json, service-pdf/composer.lock, tests/composer.lock
Weekly dependabot rollup updates
-  composer 
- npm
- run  `scripts/run_outdated_scripts/update_outdated.sh`
N/A
=> weekly dependabot rollup package updates

service-front/module/Application/view/application/general/home/accessibility.twig
Accessibility statement to be updated with a new date of completion
Fixes LPAL-324
Updates the required content
=> LPAL-324 - Accessibility statement to be updated with new date of completion

service-admin/composer.lock, service-api/composer.lock, service-front/composer.lock, service-front/package-lock.json, service-pdf/composer.lock, tests/composer.lock
Weekly dependabot updates for NPM and Composer.
- run `scripts/run_outdated_scripts/update_outdated.sh`
N/A
=> weekly dependabot updates 08-03-2021

service-front/module/Application/view/application/general/home/accessibility.twig
Amendment to created/updated section needed for the Accessibility statement 
Fixes LPAL-328
=> LPAL-328 - Accessibility statement - amendment to created/updated section needed

service-admin/composer.lock, service-api/composer.lock, service-front/composer.lock, service-front/package-lock.json, service-pdf/composer.lock, tests/composer.lock
to update 
- composer
- npm
run `scripts/run_outdated_scripts/update_outdated.sh`
=> weekly update of packages

cypress/integration/common/i_log_in.js, cypress/integration/common/i_visit.js, cypress/support/commands.js, service-front/config/autoload/global.php, service-front/module/Application/src/Form/Validator/Csrf.php
_Extra logging for CSRF_
_extra logging around CSRF problems_
=> Extra logging for CSRF problem and turn off sleep

terraform/environment/cloudwatch_alarms.tf
remove over reporting alrm for CSRF. we might reinstate if we needed.
=> disable CSRF alarm.

cypress/integration/Signup.feature, service-front/module/Application/src/Controller/Authenticated/AboutYouController.php, service-front/module/Application/src/Controller/Authenticated/ChangeEmailAddressController.php, service-front/module/Application/src/Controller/Authenticated/ChangePasswordController.php, service-front/module/Application/view/application/authenticated/about-you/index.twig, service-front/module/Application/view/application/authenticated/change-email-address/index.twig, service-front/module/Application/view/application/authenticated/change-password/index.twig
https://opgtransform.atlassian.net/browse/LPAL-210
Fixes LPAL-210
Add some buttons.
Don't make things more complicated than they need to be.
=> LPAL-210 Cancel buttons on your details pages

.circleci/config.yml, scripts/pipeline/set_environment_variables/set_slack_notify_production_release.sh, scripts/pipeline/set_environment_variables/set_slack_post_environment_domains.sh
use dynamic templates instead to generate slack message.
Fixes LPAL-352
create new slack message template shell files which will be used to create env vars, that the orb can then parse.
- Dynamic Templates: https://github.com/CircleCI-Public/slack-orb/wiki/Dynamic-Templates
=> Lpal 352 attempt3 of slack orb

.circleci/config.yml, scripts/pipeline/set_environment_variables/set_slack_env_vars.sh, scripts/pipeline/set_environment_variables/set_slack_notify_production_release.sh, scripts/pipeline/set_environment_variables/set_slack_post_environment_domains.sh
fix the issue with squashed merge commit message
Fixes LPAL-352
we now sanitise for newlines to `\n` double quotes to `\"` and `*` to `-`
Slack orbs v4 needs some work. if this works on production path to live, we'll leave it otherwise I may revert back to v3..
=> issues with squashed merge commit message

service-admin/src/App/src/Middleware/Session/JwtAuthenticationFactory.php
https://opgtransform.atlassian.net/jira/software/projects/LPAL/boards/173?selectedIssue=LPAL-27
Fixes LPAL-27
* Add HttpOnly=true
* Make use of PHP 7's extended setcookie() function to also add SameSite=Strict
n/a
=> LPAL-27 Tighten cookie security for admin UI

.circleci/config.yml, cypress/S3Monitor.py, cypress/integration/DonorHW.feature, cypress/integration/DonorPF.feature, cypress/integration/common/a11y.js, cypress/integration/common/i_click.js, cypress/start.sh, cypress/support/axe_wrapper.js, cypress/support/commands.js
_LPAL-346 remove even more dup a11y checks_
_if url already checked, don't recheck_
=> LPAL-346 remove even more dup a11y checks

terraform/account/elasticache.tf
ACCOUNT LEVEL CHANGE. please approve first.
part fix for LPAL-363
rename the elasticache to relate to the component we use it for.
=> recreate  elasticache with a name relating to component

docker-compose.yml, local-config/Dockerfile, local-config/start.sh, service-pdf/src/Opg/Lpa/Pdf/Worker/AbstractWorker.php, service-pdf/src/Opg/Lpa/Pdf/Worker/SqsWorker.php
Fixes [LPAL-384](https://opgtransform.atlassian.net/browse/LPAL-384)
Turn on content-based de-duplication in the localstack SQS queue. 
Additionally fix an issue with the name of the localstack S3 bucket (doesn't seem to like titlecase any more).
Remove some cruft from Dockerfile for local-config.
[awscli to work with SQS queues](https://docs.aws.amazon.com/cli/latest/reference/sqs/)
localstack UI is not worth bothering with (the pro version is probably better)
=> LPAL-384 PDF generation is slow locally

.github/workflows/report.yml
=> Add workflow for scanning

.circleci/config.yml
Urgent fixes to pipeline
- missed replacement vars on autoapproval
- fix SG replacement detection on environment plan check
Fixes LPAL-452
fix config yaml entry for the plan check to new variable syntax for the slack replacement vars.
add another filter check for `aws_security*` so we do have further confidence in the plan detection on environments
N/A
=> LPAL-452 urgent fix for pipeline

service-front/module/Application/view/application/general/auth/index.twig, service-front/module/Application/view/application/general/register/index.twig
_LPAL-441 add links to Use an LPA to sign-in and create-an-account pages_
_add new paras to twigs_
=> LPAL-441 links to Use an LPA

.github/workflows/tfsec-analysis.yml
Add TFSEC scanning to the repo using security tab.
Fixes LPAL-413
- add [aquasecurity/tf-sarif-action](https://github.com/aquasecurity/tfsec-sarif-action)
=> LPAL-413 Create tfsec-analysis.yml to run code scan of TFSEC.

.circleci/config.yml, service-admin/docker/app/Dockerfile, service-api/docker/app/Dockerfile, service-front/docker/app/Dockerfile
_LPAL-407 upgrade php docker containers to fix vulnerability_
_update Dockerfiles_
=> lpal- 407 upgrade php docker containers

service-admin/docker/app/Dockerfile, service-api/docker/app/Dockerfile, service-front/docker/app/Dockerfile, tests/Dockerfile
this resolves docker dependabot PR's en-masse for Composer.
Fixes LPAL-472
update composer docker files
N/A
=> LPAL-472 update to composer 2.1.5

.github/workflows/codeql.yml
Introduce a non-blocking github action that scans python code within the repo via codeql which will then report to the security tab
Fixes LPAL-476
=> LPAL-476 - add codeql github action to capture analysis of python

service-front/module/Application/view/application/general/home/index.twig
Fixes [LPAL-464](https://opgtransform.atlassian.net/browse/LPAL-464)
n/a
n/a
=> LPAL-464 Add LPA survey link to homepage

service-front/module/Application/view/application/general/home/accessibility.twig
Fixes [LPAL-469](https://opgtransform.atlassian.net/browse/LPAL-469)
n/a
n/a
=> LPAL-469 Update accessibility statement

service-admin/docker/app/Dockerfile, service-api/docker/app/Dockerfile, service-front/docker/app/Dockerfile, service-pdf/docker/app/Dockerfile, service-seeding/docker/app/Dockerfile
to mitigate critical CVE-2021-36159 (see https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-36159), and to also fix some of the other minor issues detected.
Fixes LPAL-481
adjust affected dockerfiles to fix CVE.
=> Lpal-481 CVE 2021 36159 docker upgrades

.circleci/config.yml, scripts/pipeline/check_ecr_scan_results/aws_ecr_scan_results.py, scripts/pipeline/check_ecr_scan_results/templates/no_scan_results.j2, service-perfplat/docker/Dockerfile-worker-ci, service-perfplat/docker/Dockerfile-worker-dev
Reinstate lambda ECR scan and fix image not found error that caused issues.
Also fixed a couple of issues to do with generation of the messages.
Fixes LPAL-484
- Catch `ImageNotFoundException`, log it to console and continue findings generation.
- Fix the not found template as brackets weren't right.
- Reinstate CircleCI step.
- Correctly escape the description where present.
- fix security issues in docker files
N/A
=> Lpal-484 fix ecs lambda scan

.pre-commit-config.yaml, README.md, phpstan.neon
Fixes [LPAL-490](https://opgtransform.atlassian.net/browse/LPAL-490)
Trial and error
n/a
=> LPAL-490 Pre-commit fixes

.github/workflows/gitleaks.yml, .github/workflows/trufflehog.yml
Add github actions for
- GitLeaks
- Trufflehog
Fixes LPAL-482
- Trufflehog action: https://github.com/marketplace/actions/trufflehog-actions-scan
- GitLeaks action: https://github.com/marketplace/actions/gitleaks
=> Lpal 482 add secret scanning action

service-admin/docker/app/Dockerfile, service-api/docker/app/Dockerfile, service-front/docker/app/Dockerfile, tests/Dockerfile
upgrade composer dockerfiles to 2.1.6 en masse
update dockerfiles
N/A
=> composer upgrades 08-09-2021

service-front/assets/sass/extensions/elements/_elements-typography.scss, service-front/assets/sass/extensions/elements/_icons.scss, service-front/assets/sass/patterns/_details.scss, service-front/module/Application/view/application/authenticated/lpa/certificate-provider/index.twig
Fixes [LPAL-306](https://opgtransform.atlassian.net/browse/LPAL-306).
n/a
n/a
=> LPAL-306 Update certificate provider content

terraform/account/credentials.tf, terraform/environment/rds.tf, terraform/environment/terraform.tfvars.json
missed the version number when doing the auto upgrade.
reworked the level of the enhanced monitoring role.
Fixes LPAL-500
update tfvars file
also reworking the enhanced monitoring role which needs to be reapplied to pre and prod. state remove required from environments for the role.
N/A
=> LPAL-500 align version

service-admin/docker/app/Dockerfile, service-api/docker/app/Dockerfile, service-front/docker/app/Dockerfile, service-pdf/docker/app/Dockerfile, tests/Dockerfile
Bump composers to latest version in one go.
Update Dockerfiles
N/A
=> 27-09-2021: bump all composers to 2.1.8

service-front/module/Application/view/application/general/home/index.twig
Fixes [LPAL-542](https://opgtransform.atlassian.net/browse/LPAL-542)
n/a
n/a
=> LPAL-542 Remove survey link from homepage

CODEOWNERS
to allow webops access to this code for approvals in case of breakglass situation.
Update CODEOWNERS file
N/A
=> Update CODEOWNERS to allow access for Webops

.circleci/config.yml
to add Flask App to the Circle CI Build. 
Fixes LPAL-606
update circleci config with appropriate build steps 
Remember to add build steps for Path to live for new components.
=> Add flask app to the build properly

service-admin/docker/app/Dockerfile, service-api/docker/app/Dockerfile, service-front/docker/app/Dockerfile, service-pdf/docker/app/Dockerfile, tests/Dockerfile
To Bulk update composer on Docker Files from 2.1.9 to 2.1.11
Fixes LPAL-611
Update 5 dockerfiles which closes 5 PR's
N/A
=> LPAL-611 Bulk update composer files

.idea/php-test-framework.xml, .idea/php.xml, service-pdf/src/Opg/Lpa/Pdf/AbstractContinuationSheet.php, service-pdf/src/Opg/Lpa/Pdf/AbstractIndividualPdf.php, service-pdf/src/Opg/Lpa/Pdf/AbstractLp1.php, service-pdf/src/Opg/Lpa/Pdf/AbstractPdf.php, service-pdf/src/Opg/Lpa/Pdf/Aggregator/AbstractAggregator.php, service-pdf/src/Opg/Lpa/Pdf/Aggregator/AbstractContinuationSheetAggregator.php, service-pdf/src/Opg/Lpa/Pdf/Aggregator/ContinuationSheet1.php, service-pdf/src/Opg/Lpa/Pdf/Aggregator/ContinuationSheet2.php, service-pdf/src/Opg/Lpa/Pdf/Aggregator/Lp3.php, service-pdf/src/Opg/Lpa/Pdf/ContinuationSheet1.php, service-pdf/src/Opg/Lpa/Pdf/ContinuationSheet2.php, service-pdf/src/Opg/Lpa/Pdf/ContinuationSheet3.php, service-pdf/src/Opg/Lpa/Pdf/ContinuationSheet4.php, service-pdf/src/Opg/Lpa/Pdf/Lp1f.php, service-pdf/src/Opg/Lpa/Pdf/Lp1h.php, service-pdf/src/Opg/Lpa/Pdf/Lp3.php, service-pdf/src/Opg/Lpa/Pdf/Lpa120.php, service-pdf/src/Opg/Lpa/Pdf/PdftkFactory.php, service-pdf/src/Opg/Lpa/Pdf/Traits/LongContentTrait.php, service-pdf/src/Opg/Lpa/Pdf/Worker/AbstractWorker.php, service-pdf/src/Opg/Lpa/Pdf/Worker/Response/AbstractResponse.php, service-pdf/src/Opg/Lpa/Pdf/Worker/Response/S3Response.php, service-pdf/src/Opg/Lpa/Pdf/Worker/Response/TestResponse.php, service-pdf/src/Opg/Lpa/Pdf/Worker/SqsWorker.php, service-pdf/src/Opg/Lpa/Pdf/Worker/TestWorker.php, service-pdf/tests/OpgTest/Lpa/Pdf/ContinuationSheet2Test.php, service-pdf/tests/OpgTest/Lpa/Pdf/Lp3Test.php
Reverts all commits for the linting work on the PDF app, due to performance issues
_Explain how your code addresses the purpose of the change_ 
=> LPAL-448 Revert all linting work

service-feedbackdb/docker/app/Dockerfile, service-front-v2/docker/app/Dockerfile, service-front/docker/app/Dockerfile, service-pdf/docker/app/Dockerfile
_Critical security issue being reported for a number of containers_
_upgrade expat to secure version_
=> LPAL 673 security fixes for expat

.circleci/config.yml
fixes path to live db dependancy
Fixes LPAL-420
update circle ci config
=> fix ptl dependency

service-perfplat/docker/Dockerfile-api-ci, service-perfplat/docker/Dockerfile-api-dev, service-perfplat/docker/Dockerfile-config-dev, service-perfplat/docker/Dockerfile-worker-ci, service-perfplat/docker/Dockerfile-worker-dev
_LPAL-696 upgrades to fix vulnerabilities_
_Mods to dockerfiles_
=> LPAL-696 fix vulnerabilities

service-front/module/Application/view/application/general/home/index.twig
_Add (temporary) survey link to Modernise to home page._
_Identical mod to twig as was previously done for LPAL-464_
=> LPAL-704 add survey link for modernise

service-front/content/guidance/People_Certificate providers.md, service-front/content/guidance/Process_Signing the LPA.md, service-front/module/Application/view/application/general/auth/index.twig, service-front/module/Application/view/application/general/home/index.twig, service-front/module/Application/view/guidance/opg-banner.twig
_Remove coronavirus-related content and links, which are now obsolete_
_Remove relevant parts of twig and md files. I have done a case insensitive grep for covid and coronavirus on the whole code base so should be no references left_
=> LPAL-780 remove coronavirus links

service-front/content/guidance/Decisions_Preferences and instructions.md
Changes to content under the Instructions guidance are to be made so Make an LPA aligns with form LP12 
Fixes LPAL-712
_Explain how your code addresses the purpose of the change_ 
=> LPAL-712 - Guidance content change

docs/architecture/0010-support-infrastructure-regionality.md
to write up the DR and regionality infra ADR retrospectively, and cover some of the topics that might also need addressing in consequences
Fixes LPAL-583
create an ADR
N/A
=> LPAL-583 new retrospective ADR for regionality

docs/runbooks/terraform_state_locks.md
Provide details on unlocking state files within this code base
=> Markdown on unlocking state

service-front/module/Application/view/email/notify.EMAIL_LPA_REGISTRATION_WITH_CHEQUE_PAYMENT2.txt, service-front/module/Application/view/email/notify.EMAIL_LPA_REGISTRATION_WITH_PAYMENT1.txt
_Fixes to email templates  were done in Notify, this simply updates github to match the latest_
_Update email templates_
=> LPAL-701 email template fixes

service-front/content/guidance/People_Certificate providers.md
[LPAL-796](https://opgtransform.atlassian.net/browse/LPAL-796)
Edit markdown.
n/a
=> LPAL-796 Update certificate provider guidance

service-admin/composer.lock, service-api/composer.lock, service-front/composer.lock, tests/composer.lock
Roll-up of dependabot guzzle upgrades (only a patch version upgrade).
n/a
n/a
=> Upgrade guzzle for all components and tests

terraform/environment/modules/environment/ecs_admin.tf
Add the last two missing aws_security_group_rule descriptions
Fixes LPAL-724
Adds description attribute to resolve tfsec security alerts.
n/a
=> Add last missing security_group_rule descriptions

service-pdf/composer.lock
[LPAL-837]
Simple upgrade of guzzle.
n/a
[LPAL-837]: https://opgtransform.atlassian.net/browse/LPAL-837?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LPAL-837 Update to version 7.4.4 of guzzlehttp/guzzle in service-pdf

service-perfplat/docker/Dockerfile-worker
[LPAL-829](https://opgtransform.atlassian.net/browse/LPAL-829)
Manually update packages which cause vulnerability alerts. I removed packages which are now fixed in the base package.
n/a
=> LPAL-829 Manually update packages in perfplatworker causing vulnerability alerts

docs/runbooks/extending_workspace_time/extending_workspace.md
Following further feedback, I have added instructions on removing workspaces using the standard approach, with some additional instructions if we need a quicker destruction.
Fixes LPAL-857
new section with instructions 
N/A
=> LPAL-857 Add destruction details for workspace

cypress/e2e/CorrespondentReuse.feature, cypress/e2e/common/i_am_taken_to.js, cypress/e2e/common/i_click.js, cypress/e2e/common/i_visit.js, service-front/assets/js/moj/moj.modules/moj.polyfill.js, service-front/module/Application/view/application/authenticated/dashboard/index.twig, service-front/module/Application/view/application/authenticated/lpa/correspondent/index.twig, service-front/module/Application/view/layout/layout.twig, tests/python-api-client/lpaapi.py
[LPAL-753](https://opgtransform.atlassian.net/browse/LPAL-753)
See ticket.
n/a
=> LPAL-753 Axe a11y violations fixes 

Makefile, docker-compose.yml, local-ssl/docker/Dockerfile, service-admin/docker/app/Dockerfile, service-api/docker/app/Dockerfile, service-feedbackdb/docker/app/Dockerfile, service-front-v2/docker/app/Dockerfile, service-front/docker/app/Dockerfile, service-pdf/docker/app/Dockerfile, service-perfplat/docker/Dockerfile-config-dev, service-perfplat/docker/Dockerfile-worker, service-seeding/docker/app/Dockerfile
[LPAL-922](https://opgtransform.atlassian.net/browse/LPAL-922)
[LPAL-923](https://opgtransform.atlassian.net/browse/LPAL-923)
* Update Dockerfiles so they update/upgrade packages during build
* Make names for containers and images consistent in the docker-compose config
* Fix Makefile command to login to our feedback image ECR
* Reduce number of times we pull the composer image
n/a
=> LPAL-922/LPAL-923 Various security fixes and cleanup of docker-compose

Makefile, cypress/cypress_runner.py, cypress/user_number.py
[LPAL-929](https://opgtransform.atlassian.net/browse/LPAL-929)
Fixes for running cypress locally, missing while working on LPAL-911.
n/a
=> LPAL-929 Local cypress fixes

service-front/assets/js/govuk/stageprompt.js
[LPAL-94](https://opgtransform.atlassian.net/browse/LPAL-94)
See ticket.
n/a
=> LPAL-94 Add note to stageprompt JS explaining that we are maintaining it here

terraform/region/secrets.tf
Unblock pipeline
Fixes LPAL-934
Remove reference to no longer existing user
n/a
=> LPAL-934 Update reference to feedback actions user

service-front/content/guidance/Process_If you find a mistake.md, service-front/module/Application/tests/View/StatusViewModelHelperTest.php, service-front/module/Application/view/application/authenticated/lpa/certificate-provider/index.twig, service-front/module/Application/view/application/authenticated/lpa/status/index.twig
[LPAL-903](https://opgtransform.atlassian.net/browse/LPAL-903)
[LPAL-924](https://opgtransform.atlassian.net/browse/LPAL-924)
[LPAL-925](https://opgtransform.atlassian.net/browse/LPAL-925)
Rolled three issues into one branch as they only touch HTML.
n/a
=> LPAL-903/LPAL-925/LPAL-924 Content amendments

service-front/assets/sass/_opg-lpa-dashboard.scss, service-front/assets/sass/patterns/_lpa-list.scss, service-front/assets/sass/settings/_variables.scss, service-front/module/Application/view/application/authenticated/dashboard/macros.twig
[LPAL-887](https://opgtransform.atlassian.net/browse/LPAL-887)
See ticket.
n/a
=> LPAL-887 Improve contrast on status dashboard

service-front/config/autoload/global.php, service-front/module/Application/src/Controller/General/AuthController.php, service-front/module/Application/tests/Controller/General/AuthControllerTest.php
[LPAL-769](https://opgtransform.atlassian.net/browse/LPAL-769)
See ticket for context.
n/a
=> LPAL-769 Session fixes based on ASVS recommendations

.github/workflows/workflow_terraform_environment_cleanup.yml
Add missing env variable for TF destroy in environment cleanup
Fixes LPAL-978
Add TF_VAR_pagerduty_token to Terraform
=> LPAL-978 Fix Cleanup environment

cypress/e2e/DateCheck.feature, cypress/e2e/common/date_check.js
[LPAL-913](https://opgtransform.atlassian.net/browse/LPAL-913)
See ticket
n/a
=> LPAL-913 Add steps to check visually-hidden donor dates info

service-front/assets/.eslintrc.json, service-front/assets/js/moj/moj.ga-tracker.js, service-front/assets/js/opg/cache-busting.js, service-front/assets/js/opg/session-timeout-dialog.js
_Fix no-redeclare errors from eslint for application js_
_Fix errors from eslint. These had to be done by hand as linter doesn't auto-fix these_
=> LPAL-996 fix no-redeclare errors from eslint for application js

.github/workflows/workflow_path_to_live.yml, .github/workflows/workflow_pr.yml
Improve the Post-Deployment message on Live deployment and post a message containing URLs to dev channel for dev envs
Fixes LPAL-1010
=> LPAL-1010 Improve post deployment msg

.github/workflows/workflow_path_to_live.yml
Fix equals sign syntax error in Path to Live
Fixes LPAL-1010
=> LPAL-1010 Fix syntax error in Path to Live

cypress/e2e/AttorneysHW.feature, service-front/assets/js/moj/moj.modules/moj.person-form.js
_Fix minor typo in warning text_
_Fix js code and cypress test_
=> LPAL-1031 fix old typo in warning text

cypress/e2e/AttorneysHW.feature, cypress/e2e/DonorHW.feature, cypress/e2e/ReplacementAttorneysHW.feature, service-front/assets/js/moj/moj.modules/moj.person-form.js
[LPAL-1032](https://opgtransform.atlassian.net/browse/LPAL-1032)
See ticket.
n/a
=> LPAL-1032 Error message when actor is > 100 years old should include their type (donor, attorney etc.)

service-front/module/Application/src/Model/Service/ServiceAbstractFactory.php, service-front/module/Application/src/Model/Service/Session/FilteringSaveHandler.php, service-front/module/Application/src/Model/Service/System/Status.php, service-front/module/Application/src/Module.php, service-front/module/Application/tests/Model/Service/System/StatusTest.php, service-front/module/Application/view/application/general/ping/index.twig
[LPAL-974](https://opgtransform.atlassian.net/browse/LPAL-974)
See ticket.
n/a
=> LPAL-974 Add Redis healthcheck to system status page

service-front/module/Application/view/application/authenticated/lpa/type/index.twig
_content change on type page_
_Update content in twig file_
=> LPAL-1051 content change text on type page

.github/workflows/workflow_path_to_live.yml, .github/workflows/workflow_pr.yml
Update the PR post-deployment message in Slack
Fixes LPAL-1041
=> LPAL-1041 Update link in deployment notification

.github/workflows/workflow_weekly_refresh.yml
Prevent TF config drift by running weekly Terraform refresh
Fixes LPAL-1057
Add new workflow on a Cron schedule which runs at 6am on Wednesdays.
=> LPAL-1057 Run weekly Terraform refresh against production

docs/runbooks/cloud9/cloud9_init.sh, docs/runbooks/cloud9/db_access.md, docs/runbooks/maintenance_mode/manage_maintenance.sh
Documentation updates for DB access
Fixes LPAL-205
=> LPAL-205 Update documentation for DB access

.github/workflows/workflow_path_to_live.yml, .github/workflows/workflow_pr.yml, cypress/e2e/Admin.feature, cypress/e2e/AdminSystemMessage.feature, cypress/e2e/common/admin.js, service-admin/src/App/src/Form/AbstractForm.php, service-admin/src/App/src/Form/Feedback.php, service-admin/src/App/src/Form/SignIn.php, service-admin/src/App/src/Form/SystemMessage.php, service-admin/src/App/src/Form/UserFind.php, service-admin/src/App/src/Form/UserSearch.php, service-admin/src/App/src/Handler/UserFindHandler.php, service-admin/src/App/src/Handler/UserSearchHandler.php, service-admin/src/App/templates/app/user-find.phtml, service-admin/src/App/templates/app/user-search.phtml, service-front/module/Application/src/View/Helper/SystemMessage.php, service-front/module/Application/tests/View/Helper/SystemMessageTest.php
[LPAL-1022](https://opgtransform.atlassian.net/browse/LPAL-1022)
See ticket.
n/a
=> LPAL-1022 Filter and escape system message

scripts/pipeline/ci_ingress/ci_ingress.py
Fix the assume role logic in CI Ingress script
Fixes LPAL-1068
=> LPAL-1068 Fix assume role logic in CI ingress

terraform/account/s3.tf, terraform/email/email.tf, terraform/region/modules/region/elasticache.tf, terraform/region/modules/region/s3.tf
Replace deprecated Terraform code with updated code
Fixes LPAL-1065
Replace code that has deprecation warnigs.
=> LPAL-1065 Replace deprecated Terraform code

scripts/pipeline/lib/ECSMonitor.py
Do not assume an IAM role that is already assumed in pipeline to fix issue with FeedbackDB task
Fixes LPAL-1086
=> LPAL-1086 Don't assume role unnecessarily

.github/workflows/workflow_path_to_live.yml, .github/workflows/workflow_pr.yml, .github/workflows/workflow_start_task.yml
Use a generic Github Actions workflow for both seeding and feedbackdb.
Fixes LPAL-1086
=> LPAL-1086 Use generic task starting workflow

.github/workflows/workflow_path_to_live.yml, .github/workflows/workflow_pr.yml
Add a Terraform plan for preproduction to preview changes in higher environments]
Fixes LPAL-1096
Add 3 workflow jobs to run a Terraform plan
=> LPAL-1096 Generate TF Preproduction plan

.github/workflows/workflow_path_to_live.yml, .github/workflows/workflow_pr.yml
Fix the Path to Live Slack messages so they get updated correctly if the workflow passes / fails
Fixes LPAL-1094
Add missing logic to run steps on failure or cancellation and fix missing text on existing conditional. Also add robot face to messages to make them stand out more.
=> LPAL-1094 Fix Path to Live Slack message updates

.github/workflows/workflow_pr.yml
Correct the workspace name for PR workflow preprod check
Fixes LPAL-1106
=> LPAL-1106 Correct workspace name for preprod check

.github/workflows/workflow_path_to_live.yml, .github/workflows/workflow_pr.yml
Remove cancel in progress for Github Actions to avoid TF state locks
Fixes LPAL-1093
=> LPAL-1093 Remove cancel in progress for  Actions

terraform/environment/terraform.tfvars.json
Enable cross-region Aurora backup in production
Fixes LPAL-1092
Enable in Terraform variables JSON file
=> LPAL-1092 Enable cross-region backup in prod

.github/workflows/workflow_destroy_on_merge.yml
Fix working directory
Fixes LPAL-1115
=> LPAL-1115 Adding working directory

terraform/environment/modules/environment/ecs_admin.tf, terraform/environment/modules/environment/ecs_api.tf, terraform/environment/modules/environment/ecs_feedbackdb.tf, terraform/environment/modules/environment/ecs_front.tf, terraform/environment/modules/environment/ecs_pdf.tf, terraform/environment/modules/environment/locals.tf
Add OpenTelemetry sidecar containers to all application tasks to enable X-Ray integration to be added to the applications
Fixes LPAL-876
Use a generic local and add this to the task definitions for all services.
https://github.com/ministryofjustice/opg-sirius-infrastructure/blob/main/environment/modules/environment/api.tf
=> LPAL-876 Add OpenTelemetry sidecar containers

.github/workflows/workflow_destroy_on_merge.yml
Use private SSH key for workspace cleanup
Fixes LPAL-1115
=> LPAL-1115 Use private SSH key for workspace cleanup

.idea/php-test-framework.xml, .idea/runConfigurations/test_front_downloadcontroller.xml, .idea/workspace.xml, cypress/e2e/Errors.feature, cypress/e2e/common/encoding.js, cypress/e2e/common/i_visit.js, cypress/support/commands.js, service-front/module/Application/src/Controller/Authenticated/Lpa/DownloadController.php, service-front/module/Application/tests/Controller/AbstractControllerTest.php, service-front/module/Application/tests/Controller/Authenticated/Lpa/DownloadControllerTest.php, service-front/module/Application/tests/Controller/Authenticated/PostcodeControllerTest.php, service-front/module/Application/tests/Controller/General/RegisterControllerTest.php
[LPAL-1105](https://opgtransform.atlassian.net/browse/LPAL-1105)
See ticket.
n/a
=> LPAL-1105 Return 404 when trying to download a PDF for an incomplete LPA

.github/workflows/workflow_weekly_refresh.yml
Fix the weekly refresh workflow
Fixes LPAL-1222
=> LPAL-1222 Remove inputs from weekly refresh

.github/workflows/analysis-tfsec-pr-commenter.yml
Bump version of PR commenter to use Github API with Github Toke
Fixes LPAL-1124
=> LPAL-1124 Bump PR Commenter version

.github/workflows/analysis-tfsec-pr-commenter.yml, .github/workflows/analysis-tfsec.yml, .github/workflows/analysis-trivy.yml
Use reusable analysis workflows
Fixes LPAL-1125
=> LPAL-1125 Use reusable workflows for analysis

cypress/Dockerfile, package-lock.json, package.json
Recreating the dependabot PR which I couldn't re-run correctly.
=> Update to cypress 12.2.0

Makefile, service-admin/docker/app/Dockerfile, service-api/docker/app/Dockerfile, service-front/docker/app/Dockerfile, service-pdf/docker/app/Dockerfile
Fixes [LPAL-1077](https://opgtransform.atlassian.net/browse/LPAL-1077)
See ticket.
n/a
[LPAL-1077]: https://opgtransform.atlassian.net/browse/LPAL-1077?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LPAL-1077 Update composer to version 2.5.1

.github/workflows/docker_job.yml
Rebuild docker images on squash and merge to main
Fixes LPAL-1128
Check if the expected images exist and build them if they don't
=> LPAL-1128 Rebuild on squash and merge to main

service-admin/composer.json, service-admin/composer.lock, service-admin/psalm.xml, service-admin/src/App/src/Middleware/Session/JwtMiddleware.php, service-admin/src/App/src/Service/Authentication/AuthenticationService.php, service-admin/src/App/src/Service/Authentication/Identity.php, service-admin/src/App/src/Service/Cache/Cache.php, service-admin/src/App/src/Service/User/UserService.php, shared/module/MakeShared/src/Psalm/SensitiveParameterAnnotationHook.php
[LPAL-1103](https://opgtransform.atlassian.net/browse/LPAL-1103)
See ticket.
n/a
[LPAL-1103]: https://opgtransform.atlassian.net/browse/LPAL-1103?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LPAL-1103 Add sensitive parameter annotation to service-admin

.github/workflows/analysis-tfsec-pr-commenter.yml
Fix the TFSec PR commenter
Fixes LPAL-1132
=> LPAL-1132 Fix TFSec PR commenter inputs

service-front/module/Application/tests/View/StatusViewModelHelperTest.php, service-front/module/Application/view/application/authenticated/lpa/status/index.twig
[LPAL-1131](https://opgtransform.atlassian.net/browse/LPAL-1131)
See ticket.
n/a
[LPAL-1131]: https://opgtransform.atlassian.net/browse/LPAL-1131?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LPAL-1131 Add link to Use an LPA for processed applications

package-lock.json
Fix file missed during dependabot update. 
n/a
n/a
=> Update package-lock.json in line with package.json

.github/workflows/cypress_tests.yml, .github/workflows/dependency-update.yml, .github/workflows/docker_job.yml, .github/workflows/phpunit.yml, .github/workflows/workflow_destroy_on_merge.yml, .github/workflows/workflow_path_to_live.yml, .github/workflows/workflow_pr.yml, .github/workflows/workflow_start_task.yml, .github/workflows/workflow_terraform_environment_cleanup.yml, .github/workflows/workflow_weekly_refresh.yml
Update the reusable Github Actions to avoid unnecessarily high number of renovate PRs
Fixes LPAL-1169
=> LPAL-1169 Update reusable Github Actions

renovate.json
[LPAL-1162](https://opgtransform.atlassian.net/browse/LPAL-1162)
see ticket
Renovate
[LPAL-1162]: https://opgtransform.atlassian.net/browse/LPAL-1162?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LPAL-1162 Fix renovate config issue

cypress/e2e/Admin.feature
Quick fix for build issue. Underlying problem looks likely to be stale cypress container.
Remove line from feature which isn't recognised by cypress.
n/a
=> Remove broken line from cypress test feature

cypress/e2e/HomePage.feature, cypress/e2e/common/headers.js, service-front/docker/web/etc/confd/templates/default.conf, service-front/module/Application/src/Controller/AbstractBaseController.php
[LPAL-1175](https://opgtransform.atlassian.net/browse/LPAL-1175)
see ticket
n/a
=> LPAL-1175 Fix Google Analytics script (and tracking image) load

.github/workflows/analysis-psalm.yml, shared/module/MakeShared/src/DataModel/Common/Address.php, shared/module/MakeShared/src/DataModel/Common/EmailAddress.php, shared/module/MakeShared/src/DataModel/Common/LongName.php, shared/module/MakeShared/src/DataModel/Common/Name.php, shared/module/MakeShared/src/DataModel/Validator/ValidatorResponse.php, shared/module/MakeShared/src/DataModel/Validator/ValidatorResponseInterface.php, shared/module/MakeShared/src/Telemetry/Event.php
[LPAL-1178](https://opgtransform.atlassian.net/browse/LPAL-1178)
Suppress and fix psalm errors caused by update to v5. These changes have no effect on the application at runtime.
n/a
[LPAL-1178]: https://opgtransform.atlassian.net/browse/LPAL-1178?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LPAL-1178 Fix psalm analysis for shared/ directory

scripts/non_live_seeding/seed_test_deletion_log.sql
Fixes [LPAL-1176](https://opgtransform.atlassian.net/browse/LPAL-1176)
[LPAL-1176]: https://opgtransform.atlassian.net/browse/LPAL-1176?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LPAL-1176 Fix seeding error

service-front/Gruntfile.js, service-front/package-lock.json
[LPAL-1181](https://opgtransform.atlassian.net/browse/LPAL-1181)
Include in Gruntfile.js
n/a
[LPAL-1181]: https://opgtransform.atlassian.net/browse/LPAL-1181?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LPAL-1181 Polyfill JS not loading in live

service-api/module/Application/src/Controller/PingController.php, service-api/module/Application/tests/Controller/PingControllerTest.php, service-front/module/Application/src/Controller/General/PingController.php, service-front/module/Application/src/Model/Service/System/Status.php, service-front/module/Application/tests/Controller/General/PingControllerTest.php, service-front/module/Application/tests/Model/Service/System/StatusTest.php, service-front/module/Application/view/application/general/ping/index.twig, shared/module/MakeShared/src/Constants.php
[LPAL-473](https://opgtransform.atlassian.net/browse/LPAL-473)
See ticket.
n/a
[LPAL-473]: https://opgtransform.atlassian.net/browse/LPAL-473?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LPAL-473 Rework /ping endpoint

README.md
=> LPAL-1198 Fix errors/omissions in README

service-front/assets/js/moj/moj.modules/moj.analytics.js
See [LPAL-1209](https://opgtransform.atlassian.net/browse/LPAL-1209)
[LPAL-1209]: https://opgtransform.atlassian.net/browse/LPAL-1209?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [LPAL-1209] Fix analytics cookie deletion

.github/workflows/locust_tests.yml, .github/workflows/workflow_path_to_live.yml
_fix build_
_mods to github action_
=> attempt 2 to fix build

service-pdf/composer.lock
Reverts ministryofjustice/opg-lpa#1565
=> Revert "Bump guzzlehttp/psr7 from 2.4.4 to 2.5.0 in /service-pdf"

package-lock.json
Rebuild due to perms.
Bumps [tough-cookie](https://github.com/salesforce/tough-cookie) and [@cypress/request](https://github.com/cypress-io/request). These dependencies needed to be updated together.
Updates `tough-cookie` from 2.5.0 to 4.1.3
- [Release notes](https://github.com/salesforce/tough-cookie/releases)
- [Changelog](https://github.com/salesforce/tough-cookie/blob/master/CHANGELOG.md)
- [Commits](https://github.com/salesforce/tough-cookie/compare/v2.5.0...v4.1.3)
Updates `@cypress/request` from 2.88.11 to 2.88.12
- [Release notes](https://github.com/cypress-io/request/releases)
- [Changelog](https://github.com/cypress-io/request/blob/master/CHANGELOG.md)
- [Commits](https://github.com/cypress-io/request/compare/v2.88.11...v2.88.12)
---
updated-dependencies:
- dependency-name: …
=> Bump tough-cookie and @cypress/request

.github/workflows/docker_job.yml
=> LPAL-1237 Always rebuild images

terraform/environment/modules/environment/ecs_api.tf, terraform/environment/modules/environment/ecs_front.tf
Increase the memory and CPU available to the front and API containers.
Fixes LPAL-1240
=> LPAL-1240 Increase resource available to container

service-admin/docker/app/Dockerfile, service-api/docker/app/Dockerfile, service-front/docker/app/Dockerfile
Upgrade base container for API, Front and Admin.
Fixes LPAL-1236
=> LPAL-1236 Upgrade base container

.github/workflows/docker_job.yml
=> LPAL-1237 Fix Path to Live

service-front/module/Application/view/guidance/opg-help-content.twig
_Add label to navigation for accessibility_
_Minor mod to twig file_
=> LPAL-1245 aria labelling as suggested by accessibility team

.github/workflows/cypress_tests.yml, .github/workflows/docker_job.yml, .github/workflows/locust_tests.yml, .github/workflows/phpunit.yml, .github/workflows/workflow_destroy_on_merge.yml, .github/workflows/workflow_pr.yml, .github/workflows/workflow_start_task.yml, .github/workflows/workflow_terraform_environment_cleanup.yml
_Fix builds going forward_
_upgrade github action_
=> upgrade aws creds github action to fix builds

service-front/module/Application/view/application/authenticated/lpa/status/index.twig, service-front/module/Application/view/application/general/home/accessibility.twig, service-front/module/Application/view/application/general/home/contact.twig, service-front/module/Application/view/email/notify.EMAIL_ACCOUNT_ACTIVATE.txt, service-front/module/Application/view/email/notify.EMAIL_ACCOUNT_DUPLICATION_WARNING.txt, service-front/module/Application/view/email/notify.EMAIL_LPA_REGISTRATION_WITH_CHEQUE_PAYMENT2.txt, service-front/module/Application/view/email/notify.EMAIL_LPA_REGISTRATION_WITH_NO_PAYMENT3.txt, service-front/module/Application/view/email/notify.EMAIL_LPA_REGISTRATION_WITH_PAYMENT1.txt, service-front/module/Application/view/email/notify.EMAIL_NEW_EMAIL_ADDRESS_NOTIFY.txt, service-front/module/Application/view/email/notify.EMAIL_NEW_EMAIL_ADDRESS_VERIFY.txt, service-front/module/Application/view/email/notify.EMAIL_PASSWORD_CHANGED.txt, service-front/module/Application/view/email/notify.EMAIL_PASSWORD_RESET.txt, service-front/module/Application/view/email/notify.EMAIL_PASSWORD_RESET_NO_ACCOUNT.txt
_Update pages and emails to reflect Contact Centre reverting to slightly earlier opening time_
_Update opening time in twig templates and email templates_
=> LPAL-10 update contact centre times back to 9am.  MERGE EARLIEST 9.30 Fri 13 Oct

renovate.json
Auto-merge updates to Github Actions
=> Automerge Github Actions updates

terraform/environment/modules/environment/load_balancer_front.tf
Correct data lookup for Route53 health checks. 
Fixes LPAL-1255
=> LPAL-1255: Correct data lookup for Route53 Healthchecks

docs/runbooks/cloud9/redis_access.md, docs/runbooks/cloud9/redis_init.py
Add a runbook for connecting to Redis via Cloud9.
Fixes LPAL-1259
=> LPAL-1259 Runbook for connecting to Redis

.github/workflows/docker_job.yml
Post ECR alerts to opg-lpa-builds
Fixes LPAL-1262
=> LPAL-1262 Post alerts to correct Slack channel

.github/workflows/workflow_path_to_live.yml
Add semver tagging for images create in Path to Live
Fixes LPAL-1212
=> LPAL-1212 Use Semver tagging for main

service-api/docker/pgbouncer/Dockerfile
Update pgbouncer base image version
=> Update pgbouncer base image version

package-lock.json
_Upgrade braces to improve security_
_update package lock_
=> UML-3403 upgrade braces

service-front/package-lock.json, service-front/package.json
_braces upgrade to improve security
_upgrade package files_
=> UML-3403 upgrade braces in 2cnd location

cypress/e2e/DonorHW.feature, cypress/e2e/DonorPF.feature, cypress/e2e/LpaTypeHW.feature, cypress/e2e/LpaTypePF.feature, cypress/e2e/LpaTypePFClone.feature, cypress/e2e/common/stubs_ordnance_survey.js, terraform/environment/modules/environment/cloudwatch_data_protection_policy.tf
Adds a data protection policy for use, which masks email address in our cloudwatch logs
Fixes LPAL-1308
=> Add cloudwatch_data_protection_policy.tf

service-api/docker/pgbouncer/Dockerfile
Update docker image version for pgbouncer
=> Update docker image

terraform/account/.envrc
Updates logic in envrc to switch to the correct terraform version
Fixes UML-3586
=> Update version handling

service-front/content/guidance/About LPAs_What is an LPA.md, service-front/content/guidance/Process_How to register the LPA.md, service-front/module/Application/view/application/authenticated/lpa/complete/complete.twig, service-front/module/Application/view/application/authenticated/lpa/complete/view-docs.twig, service-front/module/Application/view/application/authenticated/lpa/status/index.twig
_Change references to 20 weeks to 16 weeks now that processing time has improved_
_Change text in a handful of twig files and guidance MD files_
=> LPAL-1315 change 20 weeks to 16 weeks

.github/workflows/analysis-trivy.yml
Implements Trivy rate limit fix 
Fixes UML-3653
=> Add trivy rate limit fix

.github/workflows/analysis-trivy.yml
Fix the region error for the Trivy job
Fixes LPAL-1316
=> Add creds to workflow

.github/workflows/workflow_destroy_on_merge.yml
Adds Locust to the paths so the ephem environemnts can be destroyed correctly when renovate updates
Fixes LPAL-1318
=> LPAL-1318: add locust to workflow paths

.github/workflows/analysis-trivy.yml
Add Java db to trivy job
Fixes UML-3653
=> Add java db to trivy job

.github/workflows/workflow_pr.yml
Adding in the PR number in front of the safe branch name will help to prevent duplicate workspaces from being created.
Fixes LPAL-1324
=> LPAL-1324: include PR number

.github/workflows/workflow_destroy_on_merge.yml
Adds the event number to the workspace name for deletion
Fixes LPAL-1323
=> LPAL-1323: add event number

terraform/environment/modules/environment/cloudwatch_data_protection_policy.tf
Change data protection policy from being log group based, to being account wide
Fixes UML-3685
=> Add data protection policy

.github/workflows/workflow_destroy_on_merge.yml
Correctly aligns the length of the workspace name for deletion
Fixes LPAL-1326
=> LPAL-1326: fix workspace delete

.github/workflows/analysis-trivy.yml
Updates the role for the credentials action
Fixes uml-3711
=> Update role for action

service-front/content/guidance/About LPAs_What is an LPA.md, service-front/content/guidance/Process_How to register the LPA.md, service-front/content/guidance/Process_Signing the LPA.md, service-front/module/Application/view/application/authenticated/lpa/complete/complete.twig, service-front/module/Application/view/application/authenticated/lpa/complete/view-docs.twig, service-front/module/Application/view/application/authenticated/lpa/status/index.twig
_change 16 weeks to 8 weeks to reflect shorter processing times. also LPAL-1329 missing "of" in text_
_update twig and MD files_
=> LPAL-1328 change 16 weeks to 8 weeks to reflect shorter processing times

terraform/environment/terraform.tfvars.json
We know the service will get a lot of traffic, so we need to scale up in preparation of meeting the surge of demand.
Fixes LPAL-1343
=> LPAL-1343: scale up in prep for Money Show feature

terraform/environment/terraform.tfvars.json
Reset our scaling to normal after the Money Show feature
Fixes LPAL-1343
=> LPAL-1343: reset scaling to normal

package-lock.json
_upgrade elliptic_
_npm upgrade and commit package-lock.json_
=> UML-3668 upgrade elliptic

.github/workflows/analysis-codeql.yml, .github/workflows/analysis-eslint.yml, .github/workflows/analysis-psalm.yml, .github/workflows/analysis-tfsec-pr-commenter.yml, .github/workflows/analysis-tfsec.yml, .github/workflows/analysis-trivy.yml, .github/workflows/cypress_tests.yml, .github/workflows/dependency-update.yml, .github/workflows/docker_job.yml, .github/workflows/locust_tests.yml, .github/workflows/phpunit.yml, .github/workflows/workflow_destroy_on_merge.yml, .github/workflows/workflow_path_to_live.yml, .github/workflows/workflow_pr.yml, .github/workflows/workflow_start_task.yml, .github/workflows/workflow_terraform_environment_cleanup.yml, .github/workflows/workflow_weekly_refresh.yml, renovate.json
Changes from pinned @version, to pinned @hash
Fixes LPAL-1344
=> Renovate-pin-dependencies

service-front/content/guidance/About LPAs_Life-sustaining treatment.md
_update broken link to nhs site_
_update link in guidance page_
=> LPA-3778 update broken link to nhs site

Makefile, README.md, service-front/composer.json, service-front/composer.lock, shared/module/MakeShared/src/DataModel/Common/Address.php, shared/module/MakeShared/src/DataModel/Lpa/Document/Correspondence.php, shared/module/MakeShared/tests/DataModel/Common/AddressTest.php
Add some handy make targets for updating individual packages and checking outdated. Update Symfony validator to prove work.
=> Makefile composer

service-front/module/Application/view/application/general/home/index.twig
_added warning change fee_
Fixes LPAL-1402
=> Add warning about fee change to Make LPA sign in page added price change

renovate.json, terraform/environment/modules/environment/vpc_data_sources.tf
=> add whitelist to ignore deps

.pre-commit-config.yaml, .secrets.baseline
Changes from git-leaks to detect-secrets
Fixes UML-4060
Aligns the secret detection to match other repo's
=> UML-4060: use detect-secrets

.github/workflows/workflow_path_to_live.yml, .secrets.baseline
Fix shallow pull error from semver action.
- semver action requires fetch-depth of 0 and fetch-tags set to true
=> fix fetch to be deeper and return tags

README.md, renovate.json
=> Update docs or what PHP versions are in use

cypress/e2e/CorrespondentHW.feature, cypress/e2e/CorrespondentPF.feature, service-front/module/Application/view/application/authenticated/lpa/correspondent/index.twig
_updated checkboxes with updated classes and removed js-hidden_
Fixes LPAL-1451
=> Bug fix for correspondant page 

Makefile, service-api/composer.json, service-api/composer.lock
Add shortcuts. Test by updating symfony/validator
=> Make file api composer changes
